FROM scylladb/scylla:${SCYLLA_VERSION}

# Install sshd:
RUN yum -y update && \
    yum -y install openssh-server passwd && \
    yum clean all
RUN mkdir /var/run/sshd
RUN /usr/sbin/sshd-keygen

# Create scylla-mgmt user:
RUN useradd scylla-mgmt && echo -e "test\ntest" | (passwd --stdin scylla-mgmt)

# Supervisord configuration:
ADD etc/supervisord.conf.d/sshd.conf /etc/supervisord.conf.d/sshd.conf
