FROM scylladb/scylla:${SCYLLA_VERSION}

# Install sshd:
RUN yum -y update && \
    yum -y install openssh-server passwd && \
    yum clean all
RUN mkdir /var/run/sshd
RUN ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N ''

# Create scylla-mgmt user:
RUN useradd scylla-mgmt && echo -e "test\ntest" | (passwd --stdin scylla-mgmt)

# Supervisord configuration:
ADD etc/supervisord.conf.d/sshd.conf /etc/supervisord.conf.d/sshd.conf
