// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteClusterClusterIDReader is a Reader for the DeleteClusterClusterID structure.
type DeleteClusterClusterIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteClusterClusterIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteClusterClusterIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		body := response.Body()
		defer body.Close()

		var m json.RawMessage
		if err := json.NewDecoder(body).Decode(&m); err != nil {
			return nil, err
		}

		return nil, runtime.NewAPIError("API error", m, response.Code())
	}
}

// NewDeleteClusterClusterIDOK creates a DeleteClusterClusterIDOK with default headers values
func NewDeleteClusterClusterIDOK() *DeleteClusterClusterIDOK {
	return &DeleteClusterClusterIDOK{}
}

/*DeleteClusterClusterIDOK handles this case with default header values.

Cluster deleted
*/
type DeleteClusterClusterIDOK struct {
}

func (o *DeleteClusterClusterIDOK) Error() string {
	return fmt.Sprintf("[DELETE /cluster/{cluster_id}][%d] deleteClusterClusterIdOK ", 200)
}

func (o *DeleteClusterClusterIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
