on:
  push:
    branches:
      - master
      - 'branch-**'
  pull_request:
    types: [ opened, synchronize, reopened ]

concurrency:
  group: int-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  repair:
    name: Test repair
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Setup testing dependencies
        uses: ./.github/actions/test-setup
        with:
          scylla-version: ${{ env.scylla-version }}
          ip-family: ${{ env.ip-family }}
          raft-schema: ${{ env.raft-schema }}
          tablets: ${{ env.tablets }}
          ssl-enabled: ${{ env.ssl-enabled }}

      - name: Run tablet repair tests
        run: make pkg-integration-test IP_FAMILY=${{ env.ip-family }} SSL_ENABLED=${{ env.ssl-enabled}} PKG=./pkg/service/repair/tablet
        continue-on-error: true

      - name: Print logs dc1 node1
        run: echo "dc1nod1 logs" && docker logs scylla_manager-dc1_node_1-1
        continue-on-error: true

      - name: Print logs dc1 node2
        run: echo "dc1nod2 logs" && docker logs scylla_manager-dc1_node_2-1
        continue-on-error: true

      - name: Print logs dc1 node3
        run: echo "dc1nod3 logs" && docker logs scylla_manager-dc1_node_3-1
        continue-on-error: true

      - name: Print logs dc2 node1
        run: echo "dc2nod1 logs" && docker logs scylla_manager-dc2_node_1-1
        continue-on-error: true

      - name: Print logs dc2 node2
        run: echo "dc2nod2 logs" && docker logs scylla_manager-dc2_node_2-1
        continue-on-error: true

      - name: Print logs dc2 node3
        run: echo "dc2nod3 logs" && docker logs scylla_manager-dc2_node_3-1
        continue-on-error: true