- scylla-version: scylla:2025.1.11
  ip-family: IPV4
  tablets: disabled
  ssl-enabled: true

- scylla-version: scylla:2025.1.11
  ip-family: IPV6
  tablets: enabled
  ssl-enabled: false

- scylla-version: scylla:2025.3.7
  ip-family: IPV4
  tablets: enabled
  ssl-enabled: true
  backup-method: rclone
  restore-method: native

- scylla-version: scylla:2025.3.7
  ip-family: IPV6
  tablets: disabled
  ssl-enabled: false
  backup-method: rclone
  restore-method: rclone

- scylla-version: scylla:2025.4.3
  ip-family: IPV4
  tablets: disabled
  ssl-enabled: true
  backup-method: native
  restore-method: rclone

- scylla-version: scylla:2025.4.3
  ip-family: IPV6
  tablets: enabled
  ssl-enabled: false
  backup-method: rclone
  restore-method: rclone

- scylla-version: scylla:2026.1.0
  ip-family: IPV4
  tablets: enabled
  ssl-enabled: true
  backup-method: native
  restore-method: native

- scylla-version: scylla:2026.1.0
  ip-family: IPV6
  tablets: disabled
  ssl-enabled: false
  backup-method: rclone
  restore-method: rclone

- scylla-version: scylla-nightly:latest
  ip-family: IPV4
  tablets: disabled
  ssl-enabled: true
  backup-method: native
  restore-method: native

- scylla-version: scylla-nightly:latest
  ip-family: IPV6
  tablets: enabled
  ssl-enabled: false
  backup-method: rclone
  restore-method: rclone
