- scylla-version: scylla-enterprise:2024.1.15
  ip-family: IPV4
  raft-schema: disabled
  tablets: none
  ssl-enabled: true

- scylla-version: scylla-enterprise:2024.1.15
  ip-family: IPV6
  raft-schema: enabled
  tablets: none
  ssl-enabled: false

- scylla-version: scylla-enterprise:2024.2.7
  ip-family: IPV4
  raft-schema: none
  tablets: none
  ssl-enabled: false

- scylla-version: scylla-enterprise:2024.2.7
  ip-family: IPV6
  raft-schema: none
  tablets: none
  ssl-enabled: true

- scylla-version: scylla:2025.1.0
  ip-family: IPV4
  raft-schema: none
  tablets: disabled
  ssl-enabled: true

- scylla-version: scylla:2025.1.0
  ip-family: IPV6
  raft-schema: none
  tablets: enabled
  ssl-enabled: false

- scylla-version: scylla-nightly:latest
  ip-family: IPV4
  raft-schema: none
  tablets: disabled
  ssl-enabled: true

- scylla-version: scylla-nightly:latest
  ip-family: IPV6
  raft-schema: none
  tablets: enabled
  ssl-enabled: false
