- scylla-version: scylla:2025.1.12
  ip-family: IPV4
  tablets: disabled
  ssl-enabled: true

- scylla-version: scylla:2025.1.12
  ip-family: IPV6
  tablets: enabled
  ssl-enabled: false

- scylla-version: scylla:2025.4.7
  ip-family: IPV4
  tablets: disabled
  ssl-enabled: true
  backup-method: native
  restore-method: rclone

- scylla-version: scylla:2025.4.7
  ip-family: IPV6
  tablets: enabled
  ssl-enabled: false
  backup-method: rclone
  restore-method: rclone

- scylla-version: scylla:2026.1.1
  ip-family: IPV4
  tablets: enabled
  ssl-enabled: true
  backup-method: native
  restore-method: native

- scylla-version: scylla:2026.1.1
  ip-family: IPV6
  tablets: disabled
  ssl-enabled: false
  backup-method: rclone
  restore-method: rclone
  backup-provider: localstorage

- scylla-version: scylla-nightly:latest
  ip-family: IPV4
  tablets: disabled
  ssl-enabled: true
  backup-method: native
  restore-method: native

- scylla-version: scylla-nightly:latest
  ip-family: IPV6
  tablets: enabled
  ssl-enabled: false
  backup-method: rclone
  restore-method: rclone
