- scylla-version: scylla-enterprise:2023.1.11
  ip-family: IPV4
  raft-schema: disabled
  tablets: none

- scylla-version: scylla-enterprise:2023.1.11
  ip-family: IPV4
  raft-schema: enabled
  tablets: none

- scylla-version: scylla-enterprise:2023.1.11
  ip-family: IPV6
  raft-schema: enabled
  tablets: none

- scylla-version: scylla-enterprise:2024.1.12
  ip-family: IPV4
  raft-schema: none
  tablets: none

- scylla-version: scylla-enterprise:2024.1.12
  ip-family: IPV6
  raft-schema: none
  tablets: none

- scylla-version: scylla:6.2.0
  ip-family: IPV4
  raft-schema: none
  tablets: disabled

- scylla-version: scylla:6.2.0
  ip-family: IPV4
  raft-schema: none
  tablets: enabled

- scylla-version: scylla:6.2.0
  ip-family: IPV6
  raft-schema: none
  tablets: enabled

- scylla-version: scylla-enterprise-nightly:latest-enterprise
  ip-family: IPV4
  raft-schema: none
  tablets: disabled

- scylla-version: scylla-enterprise-nightly:latest-enterprise
  ip-family: IPV4
  raft-schema: none
  tablets: enabled