- scylla-version: scylla-nightly:2025.4.0-rc0-0.20251001.a9f4024c1b57
  ip-family: IPV4
  raft-schema: none
  tablets: enabled
  ssl-enabled: true
  backup-method: native
  restore-method: rclone

- scylla-version: scylla-nightly:2025.4.0-rc0-0.20251001.a9f4024c1b57
  ip-family: IPV6
  raft-schema: none
  tablets: disabled
  ssl-enabled: false
  backup-method: rclone
  restore-method: rclone

- scylla-version: scylla-nightly:latest
  ip-family: IPV4
  raft-schema: none
  tablets: disabled
  ssl-enabled: true
  backup-method: native
  restore-method: native

- scylla-version: scylla-nightly:latest
  ip-family: IPV6
  raft-schema: none
  tablets: enabled
  ssl-enabled: false
  backup-method: rclone
  restore-method: rclone
