- scylla-version: scylla:2026.2.5
  ip-family: IPV4
  tablets: enabled
  ssl-enabled: true
  backup-method: native
  restore-method: native
  backup-provider: gcs

- scylla-version: scylla:2026.2.5
  ip-family: IPV4
  tablets: disabled
  ssl-enabled: false
  backup-method: native
  restore-method: rclone
  backup-provider: gcs

- scylla-version: scylla-nightly:latest
  ip-family: IPV4
  tablets: disabled
  ssl-enabled: true
  backup-method: native
  restore-method: native
  backup-provider: gcs

- scylla-version: scylla-nightly:latest
  ip-family: IPV6
  tablets: enabled
  ssl-enabled: false
  backup-method: rclone
  restore-method: rclone
