- scylla-version: scylla-enterprise:2023.1.11
  ip-family: IPV4
  raft-schema: disabled
  tablets: none
  ssl-enabled: true

- scylla-version: scylla-enterprise:2023.1.11
  ip-family: IPV4
  raft-schema: enabled
  tablets: none
  ssl-enabled: true

- scylla-version: scylla-enterprise:2023.1.11
  ip-family: IPV6
  raft-schema: enabled
  tablets: none
  ssl-enabled: true

- scylla-version: scylla-enterprise:2024.1.12
  ip-family: IPV4
  raft-schema: none
  tablets: none
  ssl-enabled: true

- scylla-version: scylla-enterprise:2024.1.12
  ip-family: IPV6
  raft-schema: none
  tablets: none
  ssl-enabled: true

- scylla-version: scylla:6.2.0
  ip-family: IPV4
  raft-schema: none
  tablets: disabled
  ssl-enabled: true

- scylla-version: scylla:6.2.0
  ip-family: IPV4
  raft-schema: none
  tablets: enabled
  ssl-enabled: true

- scylla-version: scylla:6.2.0
  ip-family: IPV6
  raft-schema: none
  tablets: enabled
  ssl-enabled: false

- scylla-version: scylla-enterprise-nightly:latest-enterprise
  ip-family: IPV4
  raft-schema: none
  tablets: disabled
  ssl-enabled: true

- scylla-version: scylla-enterprise-nightly:latest-enterprise
  ip-family: IPV4
  raft-schema: none
  tablets: enabled
  ssl-enabled: false
