- scylla-version: scylla:2025.2.0
  ip-family: IPV4
  raft-schema: none
  tablets: disabled
  ssl-enabled: true

- scylla-version: scylla:2025.2.0
  ip-family: IPV6
  raft-schema: none
  tablets: enabled
  ssl-enabled: false
