- scylla-version: scylla-enterprise:2023.1.9
  ip-family: IPV4
  raft-schema: disabled
  tablets: none

- scylla-version: scylla-enterprise:2023.1.9
  ip-family: IPV4
  raft-schema: enabled
  tablets: none

- scylla-version: scylla-enterprise:2023.1.9
  ip-family: IPV6
  raft-schema: enabled
  tablets: none

- scylla-version: scylla-enterprise:2024.1.5
  ip-family: IPV4
  raft-schema: none
  tablets: none

- scylla-version: scylla-enterprise:2024.1.5
  ip-family: IPV6
  raft-schema: none
  tablets: none

- scylla-version: scylla:6.0.1
  ip-family: IPV4
  raft-schema: none
  tablets: disabled

- scylla-version: scylla:6.0.1
  ip-family: IPV4
  raft-schema: none
  tablets: enabled

- scylla-version: scylla:6.0.1
  ip-family: IPV6
  raft-schema: none
  tablets: enabled

- scylla-version: scylla-enterprise-nightly:latest-enterprise
  ip-family: IPV4
  raft-schema: none
  tablets: disabled

- scylla-version: scylla-enterprise-nightly:latest-enterprise
  ip-family: IPV4
  raft-schema: none
  tablets: enabled