// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetSavedCachesLocationReader is a Reader for the GetSavedCachesLocation structure.
type GetSavedCachesLocationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSavedCachesLocationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetSavedCachesLocationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetSavedCachesLocationOK creates a GetSavedCachesLocationOK with default headers values
func NewGetSavedCachesLocationOK() *GetSavedCachesLocationOK {
	return &GetSavedCachesLocationOK{}
}

/*GetSavedCachesLocationOK handles this case with default header values.

GetSavedCachesLocationOK get saved caches location o k
*/
type GetSavedCachesLocationOK struct {
	Payload string
}

func (o *GetSavedCachesLocationOK) Error() string {
	return fmt.Sprintf("[GET /storage_service/saved_caches/location][%d] getSavedCachesLocationOK  %+v", 200, o.Payload)
}

func (o *GetSavedCachesLocationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
