// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetAllSpeculativeRetriesReader is a Reader for the GetAllSpeculativeRetries structure.
type GetAllSpeculativeRetriesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAllSpeculativeRetriesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAllSpeculativeRetriesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAllSpeculativeRetriesOK creates a GetAllSpeculativeRetriesOK with default headers values
func NewGetAllSpeculativeRetriesOK() *GetAllSpeculativeRetriesOK {
	return &GetAllSpeculativeRetriesOK{}
}

/*GetAllSpeculativeRetriesOK handles this case with default header values.

GetAllSpeculativeRetriesOK get all speculative retries o k
*/
type GetAllSpeculativeRetriesOK struct {
	Payload int32
}

func (o *GetAllSpeculativeRetriesOK) Error() string {
	return fmt.Sprintf("[GET /column_family/metrics/speculative_retries][%d] getAllSpeculativeRetriesOK  %+v", 200, o.Payload)
}

func (o *GetAllSpeculativeRetriesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
