// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCreateHintCountParams creates a new GetCreateHintCountParams object
// with the default values initialized.
func NewGetCreateHintCountParams() *GetCreateHintCountParams {
	var ()
	return &GetCreateHintCountParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCreateHintCountParamsWithTimeout creates a new GetCreateHintCountParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCreateHintCountParamsWithTimeout(timeout time.Duration) *GetCreateHintCountParams {
	var ()
	return &GetCreateHintCountParams{

		timeout: timeout,
	}
}

// NewGetCreateHintCountParamsWithContext creates a new GetCreateHintCountParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCreateHintCountParamsWithContext(ctx context.Context) *GetCreateHintCountParams {
	var ()
	return &GetCreateHintCountParams{

		Context: ctx,
	}
}

// NewGetCreateHintCountParamsWithHTTPClient creates a new GetCreateHintCountParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCreateHintCountParamsWithHTTPClient(client *http.Client) *GetCreateHintCountParams {
	var ()
	return &GetCreateHintCountParams{
		HTTPClient: client,
	}
}

/*GetCreateHintCountParams contains all the parameters to send to the API endpoint
for the get create hint count operation typically these are written to a http.Request
*/
type GetCreateHintCountParams struct {

	/*Addr
	  The peer address

	*/
	Addr string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get create hint count params
func (o *GetCreateHintCountParams) WithTimeout(timeout time.Duration) *GetCreateHintCountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get create hint count params
func (o *GetCreateHintCountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get create hint count params
func (o *GetCreateHintCountParams) WithContext(ctx context.Context) *GetCreateHintCountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get create hint count params
func (o *GetCreateHintCountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get create hint count params
func (o *GetCreateHintCountParams) WithHTTPClient(client *http.Client) *GetCreateHintCountParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get create hint count params
func (o *GetCreateHintCountParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAddr adds the addr to the get create hint count params
func (o *GetCreateHintCountParams) WithAddr(addr string) *GetCreateHintCountParams {
	o.SetAddr(addr)
	return o
}

// SetAddr adds the addr to the get create hint count params
func (o *GetCreateHintCountParams) SetAddr(addr string) {
	o.Addr = addr
}

// WriteToRequest writes these params to a swagger request
func (o *GetCreateHintCountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param addr
	if err := r.SetPathParam("addr", o.Addr); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
