// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetDrainProgressParams creates a new GetDrainProgressParams object
// with the default values initialized.
func NewGetDrainProgressParams() *GetDrainProgressParams {

	return &GetDrainProgressParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDrainProgressParamsWithTimeout creates a new GetDrainProgressParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDrainProgressParamsWithTimeout(timeout time.Duration) *GetDrainProgressParams {

	return &GetDrainProgressParams{

		timeout: timeout,
	}
}

// NewGetDrainProgressParamsWithContext creates a new GetDrainProgressParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDrainProgressParamsWithContext(ctx context.Context) *GetDrainProgressParams {

	return &GetDrainProgressParams{

		Context: ctx,
	}
}

// NewGetDrainProgressParamsWithHTTPClient creates a new GetDrainProgressParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDrainProgressParamsWithHTTPClient(client *http.Client) *GetDrainProgressParams {

	return &GetDrainProgressParams{
		HTTPClient: client,
	}
}

/*GetDrainProgressParams contains all the parameters to send to the API endpoint
for the get drain progress operation typically these are written to a http.Request
*/
type GetDrainProgressParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get drain progress params
func (o *GetDrainProgressParams) WithTimeout(timeout time.Duration) *GetDrainProgressParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get drain progress params
func (o *GetDrainProgressParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get drain progress params
func (o *GetDrainProgressParams) WithContext(ctx context.Context) *GetDrainProgressParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get drain progress params
func (o *GetDrainProgressParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get drain progress params
func (o *GetDrainProgressParams) WithHTTPClient(client *http.Client) *GetDrainProgressParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get drain progress params
func (o *GetDrainProgressParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetDrainProgressParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
