// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetMeanRowSizeReader is a Reader for the GetMeanRowSize structure.
type GetMeanRowSizeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMeanRowSizeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetMeanRowSizeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetMeanRowSizeOK creates a GetMeanRowSizeOK with default headers values
func NewGetMeanRowSizeOK() *GetMeanRowSizeOK {
	return &GetMeanRowSizeOK{}
}

/*GetMeanRowSizeOK handles this case with default header values.

GetMeanRowSizeOK get mean row size o k
*/
type GetMeanRowSizeOK struct {
	Payload int64
}

func (o *GetMeanRowSizeOK) Error() string {
	return fmt.Sprintf("[GET /column_family/metrics/mean_row_size/{name}][%d] getMeanRowSizeOK  %+v", 200, o.Payload)
}

func (o *GetMeanRowSizeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
