// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAllRowCacheMissParams creates a new GetAllRowCacheMissParams object
// with the default values initialized.
func NewGetAllRowCacheMissParams() *GetAllRowCacheMissParams {

	return &GetAllRowCacheMissParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllRowCacheMissParamsWithTimeout creates a new GetAllRowCacheMissParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAllRowCacheMissParamsWithTimeout(timeout time.Duration) *GetAllRowCacheMissParams {

	return &GetAllRowCacheMissParams{

		timeout: timeout,
	}
}

// NewGetAllRowCacheMissParamsWithContext creates a new GetAllRowCacheMissParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAllRowCacheMissParamsWithContext(ctx context.Context) *GetAllRowCacheMissParams {

	return &GetAllRowCacheMissParams{

		Context: ctx,
	}
}

// NewGetAllRowCacheMissParamsWithHTTPClient creates a new GetAllRowCacheMissParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAllRowCacheMissParamsWithHTTPClient(client *http.Client) *GetAllRowCacheMissParams {

	return &GetAllRowCacheMissParams{
		HTTPClient: client,
	}
}

/*GetAllRowCacheMissParams contains all the parameters to send to the API endpoint
for the get all row cache miss operation typically these are written to a http.Request
*/
type GetAllRowCacheMissParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get all row cache miss params
func (o *GetAllRowCacheMissParams) WithTimeout(timeout time.Duration) *GetAllRowCacheMissParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all row cache miss params
func (o *GetAllRowCacheMissParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all row cache miss params
func (o *GetAllRowCacheMissParams) WithContext(ctx context.Context) *GetAllRowCacheMissParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all row cache miss params
func (o *GetAllRowCacheMissParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get all row cache miss params
func (o *GetAllRowCacheMissParams) WithHTTPClient(client *http.Client) *GetAllRowCacheMissParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get all row cache miss params
func (o *GetAllRowCacheMissParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllRowCacheMissParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
