// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetTruncateRPCTimeoutReader is a Reader for the GetTruncateRPCTimeout structure.
type GetTruncateRPCTimeoutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTruncateRPCTimeoutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetTruncateRPCTimeoutOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetTruncateRPCTimeoutOK creates a GetTruncateRPCTimeoutOK with default headers values
func NewGetTruncateRPCTimeoutOK() *GetTruncateRPCTimeoutOK {
	return &GetTruncateRPCTimeoutOK{}
}

/*GetTruncateRPCTimeoutOK handles this case with default header values.

GetTruncateRPCTimeoutOK get truncate Rpc timeout o k
*/
type GetTruncateRPCTimeoutOK struct {
	Payload int32
}

func (o *GetTruncateRPCTimeoutOK) Error() string {
	return fmt.Sprintf("[GET /storage_proxy/truncate_rpc_timeout][%d] getTruncateRpcTimeoutOK  %+v", 200, o.Payload)
}

func (o *GetTruncateRPCTimeoutOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
