// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/scylladb/mermaid/scyllaclient/internal/models"
)

// GetCasPrepareEstimatedRecentHistogramReader is a Reader for the GetCasPrepareEstimatedRecentHistogram structure.
type GetCasPrepareEstimatedRecentHistogramReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCasPrepareEstimatedRecentHistogramReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetCasPrepareEstimatedRecentHistogramOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetCasPrepareEstimatedRecentHistogramOK creates a GetCasPrepareEstimatedRecentHistogramOK with default headers values
func NewGetCasPrepareEstimatedRecentHistogramOK() *GetCasPrepareEstimatedRecentHistogramOK {
	return &GetCasPrepareEstimatedRecentHistogramOK{}
}

/*GetCasPrepareEstimatedRecentHistogramOK handles this case with default header values.

GetCasPrepareEstimatedRecentHistogramOK get cas prepare estimated recent histogram o k
*/
type GetCasPrepareEstimatedRecentHistogramOK struct {
	Payload *models.EstimatedHistogram
}

func (o *GetCasPrepareEstimatedRecentHistogramOK) Error() string {
	return fmt.Sprintf("[GET /column_family/metrics/cas_prepare/estimated_recent_histogram/{name}][%d] getCasPrepareEstimatedRecentHistogramOK  %+v", 200, o.Payload)
}

func (o *GetCasPrepareEstimatedRecentHistogramOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EstimatedHistogram)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
