// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetBytesCompactedParams creates a new GetBytesCompactedParams object
// with the default values initialized.
func NewGetBytesCompactedParams() *GetBytesCompactedParams {

	return &GetBytesCompactedParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetBytesCompactedParamsWithTimeout creates a new GetBytesCompactedParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetBytesCompactedParamsWithTimeout(timeout time.Duration) *GetBytesCompactedParams {

	return &GetBytesCompactedParams{

		timeout: timeout,
	}
}

// NewGetBytesCompactedParamsWithContext creates a new GetBytesCompactedParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetBytesCompactedParamsWithContext(ctx context.Context) *GetBytesCompactedParams {

	return &GetBytesCompactedParams{

		Context: ctx,
	}
}

// NewGetBytesCompactedParamsWithHTTPClient creates a new GetBytesCompactedParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetBytesCompactedParamsWithHTTPClient(client *http.Client) *GetBytesCompactedParams {

	return &GetBytesCompactedParams{
		HTTPClient: client,
	}
}

/*GetBytesCompactedParams contains all the parameters to send to the API endpoint
for the get bytes compacted operation typically these are written to a http.Request
*/
type GetBytesCompactedParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get bytes compacted params
func (o *GetBytesCompactedParams) WithTimeout(timeout time.Duration) *GetBytesCompactedParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get bytes compacted params
func (o *GetBytesCompactedParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get bytes compacted params
func (o *GetBytesCompactedParams) WithContext(ctx context.Context) *GetBytesCompactedParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get bytes compacted params
func (o *GetBytesCompactedParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get bytes compacted params
func (o *GetBytesCompactedParams) WithHTTPClient(client *http.Client) *GetBytesCompactedParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get bytes compacted params
func (o *GetBytesCompactedParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetBytesCompactedParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
