// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetDownEndpointCountReader is a Reader for the GetDownEndpointCount structure.
type GetDownEndpointCountReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDownEndpointCountReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetDownEndpointCountOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetDownEndpointCountOK creates a GetDownEndpointCountOK with default headers values
func NewGetDownEndpointCountOK() *GetDownEndpointCountOK {
	return &GetDownEndpointCountOK{}
}

/*GetDownEndpointCountOK handles this case with default header values.

GetDownEndpointCountOK get down endpoint count o k
*/
type GetDownEndpointCountOK struct {
	Payload int32
}

func (o *GetDownEndpointCountOK) Error() string {
	return fmt.Sprintf("[GET /failure_detector/count/endpoint/down][%d] getDownEndpointCountOK  %+v", 200, o.Payload)
}

func (o *GetDownEndpointCountOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
