// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetTotalOutgoingBytesParams creates a new GetTotalOutgoingBytesParams object
// with the default values initialized.
func NewGetTotalOutgoingBytesParams() *GetTotalOutgoingBytesParams {
	var ()
	return &GetTotalOutgoingBytesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetTotalOutgoingBytesParamsWithTimeout creates a new GetTotalOutgoingBytesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetTotalOutgoingBytesParamsWithTimeout(timeout time.Duration) *GetTotalOutgoingBytesParams {
	var ()
	return &GetTotalOutgoingBytesParams{

		timeout: timeout,
	}
}

// NewGetTotalOutgoingBytesParamsWithContext creates a new GetTotalOutgoingBytesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetTotalOutgoingBytesParamsWithContext(ctx context.Context) *GetTotalOutgoingBytesParams {
	var ()
	return &GetTotalOutgoingBytesParams{

		Context: ctx,
	}
}

// NewGetTotalOutgoingBytesParamsWithHTTPClient creates a new GetTotalOutgoingBytesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetTotalOutgoingBytesParamsWithHTTPClient(client *http.Client) *GetTotalOutgoingBytesParams {
	var ()
	return &GetTotalOutgoingBytesParams{
		HTTPClient: client,
	}
}

/*GetTotalOutgoingBytesParams contains all the parameters to send to the API endpoint
for the get total outgoing bytes operation typically these are written to a http.Request
*/
type GetTotalOutgoingBytesParams struct {

	/*Peer
	  The stream peer

	*/
	Peer string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get total outgoing bytes params
func (o *GetTotalOutgoingBytesParams) WithTimeout(timeout time.Duration) *GetTotalOutgoingBytesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get total outgoing bytes params
func (o *GetTotalOutgoingBytesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get total outgoing bytes params
func (o *GetTotalOutgoingBytesParams) WithContext(ctx context.Context) *GetTotalOutgoingBytesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get total outgoing bytes params
func (o *GetTotalOutgoingBytesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get total outgoing bytes params
func (o *GetTotalOutgoingBytesParams) WithHTTPClient(client *http.Client) *GetTotalOutgoingBytesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get total outgoing bytes params
func (o *GetTotalOutgoingBytesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPeer adds the peer to the get total outgoing bytes params
func (o *GetTotalOutgoingBytesParams) WithPeer(peer string) *GetTotalOutgoingBytesParams {
	o.SetPeer(peer)
	return o
}

// SetPeer adds the peer to the get total outgoing bytes params
func (o *GetTotalOutgoingBytesParams) SetPeer(peer string) {
	o.Peer = peer
}

// WriteToRequest writes these params to a swagger request
func (o *GetTotalOutgoingBytesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param peer
	if err := r.SetPathParam("peer", o.Peer); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
