// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetLeavingNodesParams creates a new GetLeavingNodesParams object
// with the default values initialized.
func NewGetLeavingNodesParams() *GetLeavingNodesParams {

	return &GetLeavingNodesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetLeavingNodesParamsWithTimeout creates a new GetLeavingNodesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetLeavingNodesParamsWithTimeout(timeout time.Duration) *GetLeavingNodesParams {

	return &GetLeavingNodesParams{

		timeout: timeout,
	}
}

// NewGetLeavingNodesParamsWithContext creates a new GetLeavingNodesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetLeavingNodesParamsWithContext(ctx context.Context) *GetLeavingNodesParams {

	return &GetLeavingNodesParams{

		Context: ctx,
	}
}

// NewGetLeavingNodesParamsWithHTTPClient creates a new GetLeavingNodesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetLeavingNodesParamsWithHTTPClient(client *http.Client) *GetLeavingNodesParams {

	return &GetLeavingNodesParams{
		HTTPClient: client,
	}
}

/*GetLeavingNodesParams contains all the parameters to send to the API endpoint
for the get leaving nodes operation typically these are written to a http.Request
*/
type GetLeavingNodesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get leaving nodes params
func (o *GetLeavingNodesParams) WithTimeout(timeout time.Duration) *GetLeavingNodesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get leaving nodes params
func (o *GetLeavingNodesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get leaving nodes params
func (o *GetLeavingNodesParams) WithContext(ctx context.Context) *GetLeavingNodesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get leaving nodes params
func (o *GetLeavingNodesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get leaving nodes params
func (o *GetLeavingNodesParams) WithHTTPClient(client *http.Client) *GetLeavingNodesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get leaving nodes params
func (o *GetLeavingNodesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetLeavingNodesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
