// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/scylladb/mermaid/scyllaclient/internal/models"
)

// GetWriteMetricsLatencyHistogramDepricatedReader is a Reader for the GetWriteMetricsLatencyHistogramDepricated structure.
type GetWriteMetricsLatencyHistogramDepricatedReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetWriteMetricsLatencyHistogramDepricatedReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetWriteMetricsLatencyHistogramDepricatedOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetWriteMetricsLatencyHistogramDepricatedOK creates a GetWriteMetricsLatencyHistogramDepricatedOK with default headers values
func NewGetWriteMetricsLatencyHistogramDepricatedOK() *GetWriteMetricsLatencyHistogramDepricatedOK {
	return &GetWriteMetricsLatencyHistogramDepricatedOK{}
}

/*GetWriteMetricsLatencyHistogramDepricatedOK handles this case with default header values.

GetWriteMetricsLatencyHistogramDepricatedOK get write metrics latency histogram depricated o k
*/
type GetWriteMetricsLatencyHistogramDepricatedOK struct {
	Payload *models.Histogram
}

func (o *GetWriteMetricsLatencyHistogramDepricatedOK) Error() string {
	return fmt.Sprintf("[GET /storage_proxy/metrics/write/histogram][%d] getWriteMetricsLatencyHistogramDepricatedOK  %+v", 200, o.Payload)
}

func (o *GetWriteMetricsLatencyHistogramDepricatedOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Histogram)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
