// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCompactionHistoryParams creates a new GetCompactionHistoryParams object
// with the default values initialized.
func NewGetCompactionHistoryParams() *GetCompactionHistoryParams {

	return &GetCompactionHistoryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCompactionHistoryParamsWithTimeout creates a new GetCompactionHistoryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCompactionHistoryParamsWithTimeout(timeout time.Duration) *GetCompactionHistoryParams {

	return &GetCompactionHistoryParams{

		timeout: timeout,
	}
}

// NewGetCompactionHistoryParamsWithContext creates a new GetCompactionHistoryParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCompactionHistoryParamsWithContext(ctx context.Context) *GetCompactionHistoryParams {

	return &GetCompactionHistoryParams{

		Context: ctx,
	}
}

// NewGetCompactionHistoryParamsWithHTTPClient creates a new GetCompactionHistoryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCompactionHistoryParamsWithHTTPClient(client *http.Client) *GetCompactionHistoryParams {

	return &GetCompactionHistoryParams{
		HTTPClient: client,
	}
}

/*GetCompactionHistoryParams contains all the parameters to send to the API endpoint
for the get compaction history operation typically these are written to a http.Request
*/
type GetCompactionHistoryParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get compaction history params
func (o *GetCompactionHistoryParams) WithTimeout(timeout time.Duration) *GetCompactionHistoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get compaction history params
func (o *GetCompactionHistoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get compaction history params
func (o *GetCompactionHistoryParams) WithContext(ctx context.Context) *GetCompactionHistoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get compaction history params
func (o *GetCompactionHistoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get compaction history params
func (o *GetCompactionHistoryParams) WithHTTPClient(client *http.Client) *GetCompactionHistoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get compaction history params
func (o *GetCompactionHistoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetCompactionHistoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
