// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetMemtableColumnsCountReader is a Reader for the GetMemtableColumnsCount structure.
type GetMemtableColumnsCountReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMemtableColumnsCountReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetMemtableColumnsCountOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetMemtableColumnsCountOK creates a GetMemtableColumnsCountOK with default headers values
func NewGetMemtableColumnsCountOK() *GetMemtableColumnsCountOK {
	return &GetMemtableColumnsCountOK{}
}

/*GetMemtableColumnsCountOK handles this case with default header values.

GetMemtableColumnsCountOK get memtable columns count o k
*/
type GetMemtableColumnsCountOK struct {
	Payload int64
}

func (o *GetMemtableColumnsCountOK) Error() string {
	return fmt.Sprintf("[GET /column_family/metrics/memtable_columns_count/{name}][%d] getMemtableColumnsCountOK  %+v", 200, o.Payload)
}

func (o *GetMemtableColumnsCountOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
