// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/scylladb/mermaid/scyllaclient/internal/models"
)

// GetWaitingOnCommitReader is a Reader for the GetWaitingOnCommit structure.
type GetWaitingOnCommitReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetWaitingOnCommitReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetWaitingOnCommitOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetWaitingOnCommitOK creates a GetWaitingOnCommitOK with default headers values
func NewGetWaitingOnCommitOK() *GetWaitingOnCommitOK {
	return &GetWaitingOnCommitOK{}
}

/*GetWaitingOnCommitOK handles this case with default header values.

GetWaitingOnCommitOK get waiting on commit o k
*/
type GetWaitingOnCommitOK struct {
	Payload *models.Histogram
}

func (o *GetWaitingOnCommitOK) Error() string {
	return fmt.Sprintf("[GET /commit_log/metrics/waiting_on_commit][%d] getWaitingOnCommitOK  %+v", 200, o.Payload)
}

func (o *GetWaitingOnCommitOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Histogram)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
