// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetCasReadUnavailablesReader is a Reader for the GetCasReadUnavailables structure.
type GetCasReadUnavailablesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCasReadUnavailablesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetCasReadUnavailablesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetCasReadUnavailablesOK creates a GetCasReadUnavailablesOK with default headers values
func NewGetCasReadUnavailablesOK() *GetCasReadUnavailablesOK {
	return &GetCasReadUnavailablesOK{}
}

/*GetCasReadUnavailablesOK handles this case with default header values.

GetCasReadUnavailablesOK get cas read unavailables o k
*/
type GetCasReadUnavailablesOK struct {
	Payload int64
}

func (o *GetCasReadUnavailablesOK) Error() string {
	return fmt.Sprintf("[GET /storage_proxy/metrics/cas_read/unavailables][%d] getCasReadUnavailablesOK  %+v", 200, o.Payload)
}

func (o *GetCasReadUnavailablesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
