// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewLocalHostidParams creates a new LocalHostidParams object
// with the default values initialized.
func NewLocalHostidParams() *LocalHostidParams {

	return &LocalHostidParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewLocalHostidParamsWithTimeout creates a new LocalHostidParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewLocalHostidParamsWithTimeout(timeout time.Duration) *LocalHostidParams {

	return &LocalHostidParams{

		timeout: timeout,
	}
}

// NewLocalHostidParamsWithContext creates a new LocalHostidParams object
// with the default values initialized, and the ability to set a context for a request
func NewLocalHostidParamsWithContext(ctx context.Context) *LocalHostidParams {

	return &LocalHostidParams{

		Context: ctx,
	}
}

// NewLocalHostidParamsWithHTTPClient creates a new LocalHostidParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewLocalHostidParamsWithHTTPClient(client *http.Client) *LocalHostidParams {

	return &LocalHostidParams{
		HTTPClient: client,
	}
}

/*LocalHostidParams contains all the parameters to send to the API endpoint
for the local hostid operation typically these are written to a http.Request
*/
type LocalHostidParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the local hostid params
func (o *LocalHostidParams) WithTimeout(timeout time.Duration) *LocalHostidParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the local hostid params
func (o *LocalHostidParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the local hostid params
func (o *LocalHostidParams) WithContext(ctx context.Context) *LocalHostidParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the local hostid params
func (o *LocalHostidParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the local hostid params
func (o *LocalHostidParams) WithHTTPClient(client *http.Client) *LocalHostidParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the local hostid params
func (o *LocalHostidParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *LocalHostidParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
