// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// History history
//
// Compaction history information
// swagger:model History
type History struct {

	// Bytes in
	BytesIn int64 `json:"bytes_in,omitempty"`

	// Bytes out
	BytesOut int64 `json:"bytes_out,omitempty"`

	// The column family name
	Cf string `json:"cf,omitempty"`

	// The time of compaction
	CompactedAt int64 `json:"compacted_at,omitempty"`

	// The UUID
	ID string `json:"id,omitempty"`

	// The keyspace name
	Ks string `json:"ks,omitempty"`

	// rows merged
	RowsMerged HistoryRowsMerged `json:"rows_merged"`
}

// Validate validates this history
func (m *History) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *History) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *History) UnmarshalBinary(b []byte) error {
	var res History
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
