run:
  deadline: 5m
  tests: false
  skip-files:
    - _gen\.go$
    - _string\.go$
    - mock_.*\.go$
  silent: true

linters-settings:
  errcheck:
    check-blank: true
  gocognit:
    min-complexity: 50
  gocyclo:
    min-complexity: 50
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - commentedOutCode
      - evalOrder
      - hugeParam
      - importShadow
      - regexpSimplify
      - yodaStyleExpr
      - whyNoLint
  lll:
    line-length: 180
  nestif:
    min-complexity: 6

linters:
  enable-all: true
  disable:
    - exhaustive
    - exhaustivestruct
    - forbidigo
    - funlen
    - gas
    - gochecknoglobals
    - gochecknoinits
    - goerr113
    - gomnd
    - ifshort
    - interfacer
    - maligned
    - nlreturn
    - nolintlint
    - prealloc
    - wrapcheck
    - wsl

issues:
  exclude-use-default: false
  exclude:
    - at least one file in a package should have a package comment
    - cognitive complexity [\d]+ of func `\(\*Service\)\.Backup` is high
    - cognitive complexity [\d]+ of func `\(\*Service\)\.Repair` is high
    - composite literal uses unkeyed fields
    - exported function `Default.+` should have comment or be unexported
    - exported function `New.*` should have comment or be unexported
    - exported method `.*Value\..+` should have comment or be unexported
    - exported method `.+\.Key` should have comment or be unexported
    - exported method `.+\.MarshalBinary` should have comment or be unexported
    - exported method `.+\.MarshalCQL` should have comment or be unexported
    - exported method `.+\.MarshalText` should have comment or be unexported
    - exported method `.+\.MarshalUDT` should have comment or be unexported
    - exported function `New` should have comment or be unexported
    - exported method `.+\.UnmarshalBinary` should have comment or be unexported
    - exported method `.+\.UnmarshalCQL` should have comment or be unexported
    - exported method `.+\.UnmarshalText` should have comment or be unexported
    - exported method `.+\.UnmarshalUDT` should have comment or be unexported
    - exported method `.+\.Validate` should have comment or be unexported
    - exported method `.+\.WriteTo` should have comment or be unexported
    - exported method `Runner\.Run` should have comment or be unexported
    - exported type `.*Value` should have comment or be unexported
    - exported type `Option` should have comment or be unexported
    - exported var `Default.+` should have comment or be unexported
    - has json tag but is not exported
    - naked return in func `WriteTo`
    - return value of `.+\.Close` is not checked
    - return value of `net.SplitHostPort` is not checked
    - return value of `strconv.ParseBool` is not checked
    - should merge variable declaration with assignment on next line
    - should not use dot imports
