run:
  deadline: 5m
  tests: true
  skip-dirs:
    - mermaidclient/internal
    - scyllaclient/internal
  skip-files:
    - mock_.*\\.go
  silent: true

linters:
  disable-all: true
  enable:
    - goimports
