// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strings"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/scylladb/mermaid/scyllaclient/internal/agent/models"
)

// JobStatusReader is a Reader for the JobStatus structure.
type JobStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *JobStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewJobStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewJobStatusDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewJobStatusOK creates a JobStatusOK with default headers values
func NewJobStatusOK() *JobStatusOK {
	return &JobStatusOK{}
}

/*JobStatusOK handles this case with default header values.

Job details
*/
type JobStatusOK struct {
	Payload *models.Job
}

func (o *JobStatusOK) GetPayload() *models.Job {
	return o.Payload
}

func (o *JobStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Job)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewJobStatusDefault creates a JobStatusDefault with default headers values
func NewJobStatusDefault(code int) *JobStatusDefault {
	return &JobStatusDefault{
		_statusCode: code,
	}
}

/*JobStatusDefault handles this case with default header values.

Server error
*/
type JobStatusDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the job status default response
func (o *JobStatusDefault) Code() int {
	return o._statusCode
}

func (o *JobStatusDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *JobStatusDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

func (o *JobStatusDefault) Error() string {
	return fmt.Sprintf("agent [HTTP %d] %s", o._statusCode, strings.TrimRight(o.Payload.Message, "."))
}
