global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'scylla-manager'
    static_configs:
      - targets: ['192.168.200.1:5090']
  - job_name: 'scylla-agent-dc1-node1'
    static_configs:
      - targets: ['192.168.200.11:5090']
  - job_name: 'scylla-agent-dc1-node2'
    static_configs:
      - targets: ['192.168.200.12:5090']
  - job_name: 'scylla-agent-dc1-node3'
    static_configs:
      - targets: ['192.168.200.13:5090']
  - job_name: 'scylla-agent-dc2-node1'
    static_configs:
      - targets: ['192.168.200.21:5090']
  - job_name: 'scylla-agent-dc2-node2'
    static_configs:
      - targets: ['192.168.200.22:5090']
  - job_name: 'scylla-agent-dc2-node3'
    static_configs:
      - targets: ['192.168.200.23:5090']