// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// RateMovingAverage rate_moving_average
//
// A meter metric which measures mean throughput and one, five, and fifteen-minute exponentially-weighted moving average throughputs
// swagger:model RateMovingAverage

type RateMovingAverage struct {

	// Total number of events from startup
	Count int64 `json:"count,omitempty"`

	// The mean rate from startup
	MeanRate int32 `json:"mean_rate,omitempty"`

	// One, five and fifteen mintues rates
	Rates []int32 `json:"rates"`
}

/* polymorph RateMovingAverage count false */

/* polymorph RateMovingAverage mean_rate false */

/* polymorph RateMovingAverage rates false */

// Validate validates this rate moving average
func (m *RateMovingAverage) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRates(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RateMovingAverage) validateRates(formats strfmt.Registry) error {

	if swag.IsZero(m.Rates) { // not required
		return nil
	}

	return nil
}

// MarshalBinary interface implementation
func (m *RateMovingAverage) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RateMovingAverage) UnmarshalBinary(b []byte) error {
	var res RateMovingAverage
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
