# Scylla SSL enabled configuration.

native_transport_port_ssl: 9142
client_encryption_options:
    enabled: true
    certificate: /etc/scylla/db.crt
    keyfile: /etc/scylla/db.key
    truststore: /etc/scylla/ca.crt
    require_client_auth: true
