# Scylla SSL enabled configuration.
# This file is merged with testing/config/scylla.yaml during start-dev-env process when SSL_ENABLED=true.

native_transport_port_ssl: 9142
client_encryption_options:
    enabled: true
    certificate: /etc/scylla/db.crt
    keyfile: /etc/scylla/db.key
    truststore: /etc/scylla/ca.crt
    require_client_auth: true
