#!/usr/bin/env bash
#
# Copyright (C) 2017 ScyllaDB
#

set -eu -o pipefail

NODE=$(docker inspect -f '{{with index .NetworkSettings.Networks "scylla-manager_public"}}{{.IPAddress}}{{end}}' scylla-manager_dc1_node_1_1)
KEYSPACE="test_keyspace_rf3"

print_usage() {
    echo "cswrite -k [KEYSPACE]"
    echo "  -k --keyspace			keyspace to write to with c-s, default ${KEYSPACE}"
    echo
}

die() {
    echo -e "$@\n"
    print_usage
    exit 1
}

while [[ $# > 0 ]]; do
    case "$1" in
        "-k"|"--keyspace")
            KEYSPACE="$2"
            shift 2
            ;;
        "-h" | "--help")
            print_usage
            exit 0
            ;;
        -*)
            die "unknown option $1"
            ;;
    esac
done

cassandra-stress write no-warmup cl=ALL n=100000 -schema "keyspace=${KEYSPACE}" \
-mode cql3 native user=cassandra password=cassandra \
-pop seq=1..100000 -node ${NODE}
