#!/usr/bin/env bash
#
# Copyright 2018 ScyllaDB
#

set -eu -o pipefail

SSH_USER="root"
SSH_PASS="root"
SSH_IDENTITY_FILE=~/.ssh/scylla-manager-root.pem
SSH_OPTS="-o ConnectTimeout=5 -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o UserKnownHostsFile=/dev/null"

if [[ ! -f "${SSH_IDENTITY_FILE}" ]]; then
    ssh-keygen -t rsa -b 2048 -N "" -f "${SSH_IDENTITY_FILE}" > /dev/null && chmod 0400 "${SSH_IDENTITY_FILE}"
fi

for name in `docker ps -f name=mermaid_dc --format {{.Names}}`; do
    host=`docker inspect -f '{{with index .NetworkSettings.Networks "mermaid_public"}}{{.IPAddress}}{{end}}' ${name}`
    sshpass -p "${SSH_PASS}" ssh-copy-id -i "${SSH_IDENTITY_FILE}" -f ${SSH_OPTS} "${SSH_USER}@${host}" &> /dev/null
done
