#!/usr/bin/env bash
#
# Copyright (C) 2017 ScyllaDB
#

set -eu -o pipefail

SILENT=0

case "$1" in
    "--silent")
        SILENT=1
        shift 1
        ;;
esac

for name in `docker ps -f name=scylla_manager_dc --format {{.Names}}`; do
    if [[ ${SILENT} == 1 ]]; then
        docker exec ${name} $@ > /dev/null
    else
        echo "> ${name}"
        docker exec ${name} $@
    fi
done
