#!/usr/bin/env bash
#
# Copyright (C) 2017 ScyllaDB
#

set -eu -o pipefail

SILENT=0

case "$1" in
    "--silent")
        SILENT=1
        shift 1
        ;;
esac

for name in $(docker ps -f name=dc1_node -f name=dc2_node --format {{.Names}}); do
    if [[ ${SILENT} == 1 ]]; then
        docker exec ${name} bash -c "$*" > /dev/null
    else
        echo "> ${name}"
        docker exec ${name} bash -c "$*"
    fi
done