// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// BulkLoadAsyncReader is a Reader for the BulkLoadAsync structure.
type BulkLoadAsyncReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *BulkLoadAsyncReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewBulkLoadAsyncOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewBulkLoadAsyncOK creates a BulkLoadAsyncOK with default headers values
func NewBulkLoadAsyncOK() *BulkLoadAsyncOK {
	return &BulkLoadAsyncOK{}
}

/*BulkLoadAsyncOK handles this case with default header values.

BulkLoadAsyncOK bulk load async o k
*/
type BulkLoadAsyncOK struct {
	Payload string
}

func (o *BulkLoadAsyncOK) Error() string {
	return fmt.Sprintf("[GET /storage_service/bulk_load_async/{path}][%d] bulkLoadAsyncOK  %+v", 200, o.Payload)
}

func (o *BulkLoadAsyncOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
