// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewForceKeyspaceFlushParams creates a new ForceKeyspaceFlushParams object
// with the default values initialized.
func NewForceKeyspaceFlushParams() *ForceKeyspaceFlushParams {
	var ()
	return &ForceKeyspaceFlushParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewForceKeyspaceFlushParamsWithTimeout creates a new ForceKeyspaceFlushParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewForceKeyspaceFlushParamsWithTimeout(timeout time.Duration) *ForceKeyspaceFlushParams {
	var ()
	return &ForceKeyspaceFlushParams{

		timeout: timeout,
	}
}

// NewForceKeyspaceFlushParamsWithContext creates a new ForceKeyspaceFlushParams object
// with the default values initialized, and the ability to set a context for a request
func NewForceKeyspaceFlushParamsWithContext(ctx context.Context) *ForceKeyspaceFlushParams {
	var ()
	return &ForceKeyspaceFlushParams{

		Context: ctx,
	}
}

// NewForceKeyspaceFlushParamsWithHTTPClient creates a new ForceKeyspaceFlushParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewForceKeyspaceFlushParamsWithHTTPClient(client *http.Client) *ForceKeyspaceFlushParams {
	var ()
	return &ForceKeyspaceFlushParams{
		HTTPClient: client,
	}
}

/*ForceKeyspaceFlushParams contains all the parameters to send to the API endpoint
for the force keyspace flush operation typically these are written to a http.Request
*/
type ForceKeyspaceFlushParams struct {

	/*Cf
	  Comma seperated column family names

	*/
	Cf *string
	/*Keyspace
	  The keyspace to flush

	*/
	Keyspace string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the force keyspace flush params
func (o *ForceKeyspaceFlushParams) WithTimeout(timeout time.Duration) *ForceKeyspaceFlushParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the force keyspace flush params
func (o *ForceKeyspaceFlushParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the force keyspace flush params
func (o *ForceKeyspaceFlushParams) WithContext(ctx context.Context) *ForceKeyspaceFlushParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the force keyspace flush params
func (o *ForceKeyspaceFlushParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the force keyspace flush params
func (o *ForceKeyspaceFlushParams) WithHTTPClient(client *http.Client) *ForceKeyspaceFlushParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the force keyspace flush params
func (o *ForceKeyspaceFlushParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCf adds the cf to the force keyspace flush params
func (o *ForceKeyspaceFlushParams) WithCf(cf *string) *ForceKeyspaceFlushParams {
	o.SetCf(cf)
	return o
}

// SetCf adds the cf to the force keyspace flush params
func (o *ForceKeyspaceFlushParams) SetCf(cf *string) {
	o.Cf = cf
}

// WithKeyspace adds the keyspace to the force keyspace flush params
func (o *ForceKeyspaceFlushParams) WithKeyspace(keyspace string) *ForceKeyspaceFlushParams {
	o.SetKeyspace(keyspace)
	return o
}

// SetKeyspace adds the keyspace to the force keyspace flush params
func (o *ForceKeyspaceFlushParams) SetKeyspace(keyspace string) {
	o.Keyspace = keyspace
}

// WriteToRequest writes these params to a swagger request
func (o *ForceKeyspaceFlushParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Cf != nil {

		// query param cf
		var qrCf string
		if o.Cf != nil {
			qrCf = *o.Cf
		}
		qCf := qrCf
		if qCf != "" {
			if err := r.SetQueryParam("cf", qCf); err != nil {
				return err
			}
		}

	}

	// path param keyspace
	if err := r.SetPathParam("keyspace", o.Keyspace); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
