// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetAllRowCacheHitReader is a Reader for the GetAllRowCacheHit structure.
type GetAllRowCacheHitReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAllRowCacheHitReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAllRowCacheHitOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAllRowCacheHitOK creates a GetAllRowCacheHitOK with default headers values
func NewGetAllRowCacheHitOK() *GetAllRowCacheHitOK {
	return &GetAllRowCacheHitOK{}
}

/*GetAllRowCacheHitOK handles this case with default header values.

GetAllRowCacheHitOK get all row cache hit o k
*/
type GetAllRowCacheHitOK struct {
	Payload int32
}

func (o *GetAllRowCacheHitOK) Error() string {
	return fmt.Sprintf("[GET /column_family/metrics/row_cache_hit][%d] getAllRowCacheHitOK  %+v", 200, o.Payload)
}

func (o *GetAllRowCacheHitOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
