// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/scylladb/mermaid/scylla/internal/models"
)

// GetCurrentStreamsReader is a Reader for the GetCurrentStreams structure.
type GetCurrentStreamsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCurrentStreamsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetCurrentStreamsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetCurrentStreamsOK creates a GetCurrentStreamsOK with default headers values
func NewGetCurrentStreamsOK() *GetCurrentStreamsOK {
	return &GetCurrentStreamsOK{}
}

/*GetCurrentStreamsOK handles this case with default header values.

GetCurrentStreamsOK get current streams o k
*/
type GetCurrentStreamsOK struct {
	Payload []*models.StreamState
}

func (o *GetCurrentStreamsOK) Error() string {
	return fmt.Sprintf("[GET /stream_manager/][%d] getCurrentStreamsOK  %+v", 200, o.Payload)
}

func (o *GetCurrentStreamsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
