// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCoordinatorScanLatencyParams creates a new GetCoordinatorScanLatencyParams object
// with the default values initialized.
func NewGetCoordinatorScanLatencyParams() *GetCoordinatorScanLatencyParams {

	return &GetCoordinatorScanLatencyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCoordinatorScanLatencyParamsWithTimeout creates a new GetCoordinatorScanLatencyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCoordinatorScanLatencyParamsWithTimeout(timeout time.Duration) *GetCoordinatorScanLatencyParams {

	return &GetCoordinatorScanLatencyParams{

		timeout: timeout,
	}
}

// NewGetCoordinatorScanLatencyParamsWithContext creates a new GetCoordinatorScanLatencyParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCoordinatorScanLatencyParamsWithContext(ctx context.Context) *GetCoordinatorScanLatencyParams {

	return &GetCoordinatorScanLatencyParams{

		Context: ctx,
	}
}

// NewGetCoordinatorScanLatencyParamsWithHTTPClient creates a new GetCoordinatorScanLatencyParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCoordinatorScanLatencyParamsWithHTTPClient(client *http.Client) *GetCoordinatorScanLatencyParams {

	return &GetCoordinatorScanLatencyParams{
		HTTPClient: client,
	}
}

/*GetCoordinatorScanLatencyParams contains all the parameters to send to the API endpoint
for the get coordinator scan latency operation typically these are written to a http.Request
*/
type GetCoordinatorScanLatencyParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get coordinator scan latency params
func (o *GetCoordinatorScanLatencyParams) WithTimeout(timeout time.Duration) *GetCoordinatorScanLatencyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get coordinator scan latency params
func (o *GetCoordinatorScanLatencyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get coordinator scan latency params
func (o *GetCoordinatorScanLatencyParams) WithContext(ctx context.Context) *GetCoordinatorScanLatencyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get coordinator scan latency params
func (o *GetCoordinatorScanLatencyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get coordinator scan latency params
func (o *GetCoordinatorScanLatencyParams) WithHTTPClient(client *http.Client) *GetCoordinatorScanLatencyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get coordinator scan latency params
func (o *GetCoordinatorScanLatencyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetCoordinatorScanLatencyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
