// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetTotalCompactionsCompletedReader is a Reader for the GetTotalCompactionsCompleted structure.
type GetTotalCompactionsCompletedReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTotalCompactionsCompletedReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetTotalCompactionsCompletedOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetTotalCompactionsCompletedOK creates a GetTotalCompactionsCompletedOK with default headers values
func NewGetTotalCompactionsCompletedOK() *GetTotalCompactionsCompletedOK {
	return &GetTotalCompactionsCompletedOK{}
}

/*GetTotalCompactionsCompletedOK handles this case with default header values.

GetTotalCompactionsCompletedOK get total compactions completed o k
*/
type GetTotalCompactionsCompletedOK struct {
	Payload int64
}

func (o *GetTotalCompactionsCompletedOK) Error() string {
	return fmt.Sprintf("[GET /compaction_manager/metrics/total_compactions_completed][%d] getTotalCompactionsCompletedOK  %+v", 200, o.Payload)
}

func (o *GetTotalCompactionsCompletedOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
