// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetEndpointDowntimeReader is a Reader for the GetEndpointDowntime structure.
type GetEndpointDowntimeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetEndpointDowntimeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetEndpointDowntimeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetEndpointDowntimeOK creates a GetEndpointDowntimeOK with default headers values
func NewGetEndpointDowntimeOK() *GetEndpointDowntimeOK {
	return &GetEndpointDowntimeOK{}
}

/*GetEndpointDowntimeOK handles this case with default header values.

GetEndpointDowntimeOK get endpoint downtime o k
*/
type GetEndpointDowntimeOK struct {
	Payload int64
}

func (o *GetEndpointDowntimeOK) Error() string {
	return fmt.Sprintf("[GET /gossiper/downtime/{addr}][%d] getEndpointDowntimeOK  %+v", 200, o.Payload)
}

func (o *GetEndpointDowntimeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
