// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSstablesPerReadHistogramParams creates a new GetSstablesPerReadHistogramParams object
// with the default values initialized.
func NewGetSstablesPerReadHistogramParams() *GetSstablesPerReadHistogramParams {
	var ()
	return &GetSstablesPerReadHistogramParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSstablesPerReadHistogramParamsWithTimeout creates a new GetSstablesPerReadHistogramParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSstablesPerReadHistogramParamsWithTimeout(timeout time.Duration) *GetSstablesPerReadHistogramParams {
	var ()
	return &GetSstablesPerReadHistogramParams{

		timeout: timeout,
	}
}

// NewGetSstablesPerReadHistogramParamsWithContext creates a new GetSstablesPerReadHistogramParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSstablesPerReadHistogramParamsWithContext(ctx context.Context) *GetSstablesPerReadHistogramParams {
	var ()
	return &GetSstablesPerReadHistogramParams{

		Context: ctx,
	}
}

// NewGetSstablesPerReadHistogramParamsWithHTTPClient creates a new GetSstablesPerReadHistogramParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSstablesPerReadHistogramParamsWithHTTPClient(client *http.Client) *GetSstablesPerReadHistogramParams {
	var ()
	return &GetSstablesPerReadHistogramParams{
		HTTPClient: client,
	}
}

/*GetSstablesPerReadHistogramParams contains all the parameters to send to the API endpoint
for the get sstables per read histogram operation typically these are written to a http.Request
*/
type GetSstablesPerReadHistogramParams struct {

	/*Name
	  The column family name in keyspace:name format

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get sstables per read histogram params
func (o *GetSstablesPerReadHistogramParams) WithTimeout(timeout time.Duration) *GetSstablesPerReadHistogramParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get sstables per read histogram params
func (o *GetSstablesPerReadHistogramParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get sstables per read histogram params
func (o *GetSstablesPerReadHistogramParams) WithContext(ctx context.Context) *GetSstablesPerReadHistogramParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get sstables per read histogram params
func (o *GetSstablesPerReadHistogramParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get sstables per read histogram params
func (o *GetSstablesPerReadHistogramParams) WithHTTPClient(client *http.Client) *GetSstablesPerReadHistogramParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get sstables per read histogram params
func (o *GetSstablesPerReadHistogramParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get sstables per read histogram params
func (o *GetSstablesPerReadHistogramParams) WithName(name string) *GetSstablesPerReadHistogramParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get sstables per read histogram params
func (o *GetSstablesPerReadHistogramParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetSstablesPerReadHistogramParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
