// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetKeyHits1Reader is a Reader for the GetKeyHits1 structure.
type GetKeyHits1Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetKeyHits1Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetKeyHits1OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetKeyHits1OK creates a GetKeyHits1OK with default headers values
func NewGetKeyHits1OK() *GetKeyHits1OK {
	return &GetKeyHits1OK{}
}

/*GetKeyHits1OK handles this case with default header values.

GetKeyHits1OK get key hits1 o k
*/
type GetKeyHits1OK struct {
	Payload int64
}

func (o *GetKeyHits1OK) Error() string {
	return fmt.Sprintf("[GET /cache_service/metrics/key/hits][%d] getKeyHits1OK  %+v", 200, o.Payload)
}

func (o *GetKeyHits1OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
