// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetPendingTasks1Reader is a Reader for the GetPendingTasks1 structure.
type GetPendingTasks1Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPendingTasks1Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetPendingTasks1OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPendingTasks1OK creates a GetPendingTasks1OK with default headers values
func NewGetPendingTasks1OK() *GetPendingTasks1OK {
	return &GetPendingTasks1OK{}
}

/*GetPendingTasks1OK handles this case with default header values.

GetPendingTasks1OK get pending tasks1 o k
*/
type GetPendingTasks1OK struct {
	Payload int32
}

func (o *GetPendingTasks1OK) Error() string {
	return fmt.Sprintf("[GET /compaction_manager/metrics/pending_tasks][%d] getPendingTasks1OK  %+v", 200, o.Payload)
}

func (o *GetPendingTasks1OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
