// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetRangeMetricsTimeoutsRatesParams creates a new GetRangeMetricsTimeoutsRatesParams object
// with the default values initialized.
func NewGetRangeMetricsTimeoutsRatesParams() *GetRangeMetricsTimeoutsRatesParams {

	return &GetRangeMetricsTimeoutsRatesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRangeMetricsTimeoutsRatesParamsWithTimeout creates a new GetRangeMetricsTimeoutsRatesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRangeMetricsTimeoutsRatesParamsWithTimeout(timeout time.Duration) *GetRangeMetricsTimeoutsRatesParams {

	return &GetRangeMetricsTimeoutsRatesParams{

		timeout: timeout,
	}
}

// NewGetRangeMetricsTimeoutsRatesParamsWithContext creates a new GetRangeMetricsTimeoutsRatesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRangeMetricsTimeoutsRatesParamsWithContext(ctx context.Context) *GetRangeMetricsTimeoutsRatesParams {

	return &GetRangeMetricsTimeoutsRatesParams{

		Context: ctx,
	}
}

// NewGetRangeMetricsTimeoutsRatesParamsWithHTTPClient creates a new GetRangeMetricsTimeoutsRatesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRangeMetricsTimeoutsRatesParamsWithHTTPClient(client *http.Client) *GetRangeMetricsTimeoutsRatesParams {

	return &GetRangeMetricsTimeoutsRatesParams{
		HTTPClient: client,
	}
}

/*GetRangeMetricsTimeoutsRatesParams contains all the parameters to send to the API endpoint
for the get range metrics timeouts rates operation typically these are written to a http.Request
*/
type GetRangeMetricsTimeoutsRatesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get range metrics timeouts rates params
func (o *GetRangeMetricsTimeoutsRatesParams) WithTimeout(timeout time.Duration) *GetRangeMetricsTimeoutsRatesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get range metrics timeouts rates params
func (o *GetRangeMetricsTimeoutsRatesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get range metrics timeouts rates params
func (o *GetRangeMetricsTimeoutsRatesParams) WithContext(ctx context.Context) *GetRangeMetricsTimeoutsRatesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get range metrics timeouts rates params
func (o *GetRangeMetricsTimeoutsRatesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get range metrics timeouts rates params
func (o *GetRangeMetricsTimeoutsRatesParams) WithHTTPClient(client *http.Client) *GetRangeMetricsTimeoutsRatesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get range metrics timeouts rates params
func (o *GetRangeMetricsTimeoutsRatesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetRangeMetricsTimeoutsRatesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
