// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetColumnFamilyNameReader is a Reader for the GetColumnFamilyName structure.
type GetColumnFamilyNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetColumnFamilyNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetColumnFamilyNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetColumnFamilyNameOK creates a GetColumnFamilyNameOK with default headers values
func NewGetColumnFamilyNameOK() *GetColumnFamilyNameOK {
	return &GetColumnFamilyNameOK{}
}

/*GetColumnFamilyNameOK handles this case with default header values.

GetColumnFamilyNameOK get column family name o k
*/
type GetColumnFamilyNameOK struct {
	Payload []string
}

func (o *GetColumnFamilyNameOK) Error() string {
	return fmt.Sprintf("[GET /column_family/name][%d] getColumnFamilyNameOK  %+v", 200, o.Payload)
}

func (o *GetColumnFamilyNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
