// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetWriteLatencyReader is a Reader for the GetWriteLatency structure.
type GetWriteLatencyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetWriteLatencyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetWriteLatencyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetWriteLatencyOK creates a GetWriteLatencyOK with default headers values
func NewGetWriteLatencyOK() *GetWriteLatencyOK {
	return &GetWriteLatencyOK{}
}

/*GetWriteLatencyOK handles this case with default header values.

GetWriteLatencyOK get write latency o k
*/
type GetWriteLatencyOK struct {
	Payload int32
}

func (o *GetWriteLatencyOK) Error() string {
	return fmt.Sprintf("[GET /column_family/metrics/write_latency/{name}][%d] getWriteLatencyOK  %+v", 200, o.Payload)
}

func (o *GetWriteLatencyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
