// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetAllCfAllMemtablesOffHeapSizeReader is a Reader for the GetAllCfAllMemtablesOffHeapSize structure.
type GetAllCfAllMemtablesOffHeapSizeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAllCfAllMemtablesOffHeapSizeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAllCfAllMemtablesOffHeapSizeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAllCfAllMemtablesOffHeapSizeOK creates a GetAllCfAllMemtablesOffHeapSizeOK with default headers values
func NewGetAllCfAllMemtablesOffHeapSizeOK() *GetAllCfAllMemtablesOffHeapSizeOK {
	return &GetAllCfAllMemtablesOffHeapSizeOK{}
}

/*GetAllCfAllMemtablesOffHeapSizeOK handles this case with default header values.

GetAllCfAllMemtablesOffHeapSizeOK get all cf all memtables off heap size o k
*/
type GetAllCfAllMemtablesOffHeapSizeOK struct {
	Payload int64
}

func (o *GetAllCfAllMemtablesOffHeapSizeOK) Error() string {
	return fmt.Sprintf("[GET /column_family/metrics/all_memtables_off_heap_size][%d] getAllCfAllMemtablesOffHeapSizeOK  %+v", 200, o.Payload)
}

func (o *GetAllCfAllMemtablesOffHeapSizeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
