// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetAllMaxRowSizeReader is a Reader for the GetAllMaxRowSize structure.
type GetAllMaxRowSizeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAllMaxRowSizeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAllMaxRowSizeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAllMaxRowSizeOK creates a GetAllMaxRowSizeOK with default headers values
func NewGetAllMaxRowSizeOK() *GetAllMaxRowSizeOK {
	return &GetAllMaxRowSizeOK{}
}

/*GetAllMaxRowSizeOK handles this case with default header values.

GetAllMaxRowSizeOK get all max row size o k
*/
type GetAllMaxRowSizeOK struct {
	Payload int64
}

func (o *GetAllMaxRowSizeOK) Error() string {
	return fmt.Sprintf("[GET /column_family/metrics/max_row_size][%d] getAllMaxRowSizeOK  %+v", 200, o.Payload)
}

func (o *GetAllMaxRowSizeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
