// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/scylladb/mermaid/scylla/internal/models"
)

// GetAllReadLatencyHistogramDepricatedReader is a Reader for the GetAllReadLatencyHistogramDepricated structure.
type GetAllReadLatencyHistogramDepricatedReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAllReadLatencyHistogramDepricatedReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAllReadLatencyHistogramDepricatedOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAllReadLatencyHistogramDepricatedOK creates a GetAllReadLatencyHistogramDepricatedOK with default headers values
func NewGetAllReadLatencyHistogramDepricatedOK() *GetAllReadLatencyHistogramDepricatedOK {
	return &GetAllReadLatencyHistogramDepricatedOK{}
}

/*GetAllReadLatencyHistogramDepricatedOK handles this case with default header values.

GetAllReadLatencyHistogramDepricatedOK get all read latency histogram depricated o k
*/
type GetAllReadLatencyHistogramDepricatedOK struct {
	Payload models.GetAllReadLatencyHistogramDepricatedOKBody
}

func (o *GetAllReadLatencyHistogramDepricatedOK) Error() string {
	return fmt.Sprintf("[GET /column_family/metrics/read_latency/histogram/][%d] getAllReadLatencyHistogramDepricatedOK  %+v", 200, o.Payload)
}

func (o *GetAllReadLatencyHistogramDepricatedOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
