// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetKeyCacheHitRateParams creates a new GetKeyCacheHitRateParams object
// with the default values initialized.
func NewGetKeyCacheHitRateParams() *GetKeyCacheHitRateParams {
	var ()
	return &GetKeyCacheHitRateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetKeyCacheHitRateParamsWithTimeout creates a new GetKeyCacheHitRateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetKeyCacheHitRateParamsWithTimeout(timeout time.Duration) *GetKeyCacheHitRateParams {
	var ()
	return &GetKeyCacheHitRateParams{

		timeout: timeout,
	}
}

// NewGetKeyCacheHitRateParamsWithContext creates a new GetKeyCacheHitRateParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetKeyCacheHitRateParamsWithContext(ctx context.Context) *GetKeyCacheHitRateParams {
	var ()
	return &GetKeyCacheHitRateParams{

		Context: ctx,
	}
}

// NewGetKeyCacheHitRateParamsWithHTTPClient creates a new GetKeyCacheHitRateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetKeyCacheHitRateParamsWithHTTPClient(client *http.Client) *GetKeyCacheHitRateParams {
	var ()
	return &GetKeyCacheHitRateParams{
		HTTPClient: client,
	}
}

/*GetKeyCacheHitRateParams contains all the parameters to send to the API endpoint
for the get key cache hit rate operation typically these are written to a http.Request
*/
type GetKeyCacheHitRateParams struct {

	/*Name
	  The column family name in keyspace:name format

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get key cache hit rate params
func (o *GetKeyCacheHitRateParams) WithTimeout(timeout time.Duration) *GetKeyCacheHitRateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get key cache hit rate params
func (o *GetKeyCacheHitRateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get key cache hit rate params
func (o *GetKeyCacheHitRateParams) WithContext(ctx context.Context) *GetKeyCacheHitRateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get key cache hit rate params
func (o *GetKeyCacheHitRateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get key cache hit rate params
func (o *GetKeyCacheHitRateParams) WithHTTPClient(client *http.Client) *GetKeyCacheHitRateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get key cache hit rate params
func (o *GetKeyCacheHitRateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get key cache hit rate params
func (o *GetKeyCacheHitRateParams) WithName(name string) *GetKeyCacheHitRateParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get key cache hit rate params
func (o *GetKeyCacheHitRateParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetKeyCacheHitRateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
