// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetColumnFamilyNameKeyspaceParams creates a new GetColumnFamilyNameKeyspaceParams object
// with the default values initialized.
func NewGetColumnFamilyNameKeyspaceParams() *GetColumnFamilyNameKeyspaceParams {

	return &GetColumnFamilyNameKeyspaceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetColumnFamilyNameKeyspaceParamsWithTimeout creates a new GetColumnFamilyNameKeyspaceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetColumnFamilyNameKeyspaceParamsWithTimeout(timeout time.Duration) *GetColumnFamilyNameKeyspaceParams {

	return &GetColumnFamilyNameKeyspaceParams{

		timeout: timeout,
	}
}

// NewGetColumnFamilyNameKeyspaceParamsWithContext creates a new GetColumnFamilyNameKeyspaceParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetColumnFamilyNameKeyspaceParamsWithContext(ctx context.Context) *GetColumnFamilyNameKeyspaceParams {

	return &GetColumnFamilyNameKeyspaceParams{

		Context: ctx,
	}
}

// NewGetColumnFamilyNameKeyspaceParamsWithHTTPClient creates a new GetColumnFamilyNameKeyspaceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetColumnFamilyNameKeyspaceParamsWithHTTPClient(client *http.Client) *GetColumnFamilyNameKeyspaceParams {

	return &GetColumnFamilyNameKeyspaceParams{
		HTTPClient: client,
	}
}

/*GetColumnFamilyNameKeyspaceParams contains all the parameters to send to the API endpoint
for the get column family name keyspace operation typically these are written to a http.Request
*/
type GetColumnFamilyNameKeyspaceParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get column family name keyspace params
func (o *GetColumnFamilyNameKeyspaceParams) WithTimeout(timeout time.Duration) *GetColumnFamilyNameKeyspaceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get column family name keyspace params
func (o *GetColumnFamilyNameKeyspaceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get column family name keyspace params
func (o *GetColumnFamilyNameKeyspaceParams) WithContext(ctx context.Context) *GetColumnFamilyNameKeyspaceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get column family name keyspace params
func (o *GetColumnFamilyNameKeyspaceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get column family name keyspace params
func (o *GetColumnFamilyNameKeyspaceParams) WithHTTPClient(client *http.Client) *GetColumnFamilyNameKeyspaceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get column family name keyspace params
func (o *GetColumnFamilyNameKeyspaceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetColumnFamilyNameKeyspaceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
