// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetWriteMetricsUnavailablesParams creates a new GetWriteMetricsUnavailablesParams object
// with the default values initialized.
func NewGetWriteMetricsUnavailablesParams() *GetWriteMetricsUnavailablesParams {

	return &GetWriteMetricsUnavailablesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetWriteMetricsUnavailablesParamsWithTimeout creates a new GetWriteMetricsUnavailablesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetWriteMetricsUnavailablesParamsWithTimeout(timeout time.Duration) *GetWriteMetricsUnavailablesParams {

	return &GetWriteMetricsUnavailablesParams{

		timeout: timeout,
	}
}

// NewGetWriteMetricsUnavailablesParamsWithContext creates a new GetWriteMetricsUnavailablesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetWriteMetricsUnavailablesParamsWithContext(ctx context.Context) *GetWriteMetricsUnavailablesParams {

	return &GetWriteMetricsUnavailablesParams{

		Context: ctx,
	}
}

// NewGetWriteMetricsUnavailablesParamsWithHTTPClient creates a new GetWriteMetricsUnavailablesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetWriteMetricsUnavailablesParamsWithHTTPClient(client *http.Client) *GetWriteMetricsUnavailablesParams {

	return &GetWriteMetricsUnavailablesParams{
		HTTPClient: client,
	}
}

/*GetWriteMetricsUnavailablesParams contains all the parameters to send to the API endpoint
for the get write metrics unavailables operation typically these are written to a http.Request
*/
type GetWriteMetricsUnavailablesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get write metrics unavailables params
func (o *GetWriteMetricsUnavailablesParams) WithTimeout(timeout time.Duration) *GetWriteMetricsUnavailablesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get write metrics unavailables params
func (o *GetWriteMetricsUnavailablesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get write metrics unavailables params
func (o *GetWriteMetricsUnavailablesParams) WithContext(ctx context.Context) *GetWriteMetricsUnavailablesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get write metrics unavailables params
func (o *GetWriteMetricsUnavailablesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get write metrics unavailables params
func (o *GetWriteMetricsUnavailablesParams) WithHTTPClient(client *http.Client) *GetWriteMetricsUnavailablesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get write metrics unavailables params
func (o *GetWriteMetricsUnavailablesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetWriteMetricsUnavailablesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
