// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetHintsInProgressParams creates a new GetHintsInProgressParams object
// with the default values initialized.
func NewGetHintsInProgressParams() *GetHintsInProgressParams {

	return &GetHintsInProgressParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetHintsInProgressParamsWithTimeout creates a new GetHintsInProgressParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetHintsInProgressParamsWithTimeout(timeout time.Duration) *GetHintsInProgressParams {

	return &GetHintsInProgressParams{

		timeout: timeout,
	}
}

// NewGetHintsInProgressParamsWithContext creates a new GetHintsInProgressParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetHintsInProgressParamsWithContext(ctx context.Context) *GetHintsInProgressParams {

	return &GetHintsInProgressParams{

		Context: ctx,
	}
}

// NewGetHintsInProgressParamsWithHTTPClient creates a new GetHintsInProgressParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetHintsInProgressParamsWithHTTPClient(client *http.Client) *GetHintsInProgressParams {

	return &GetHintsInProgressParams{
		HTTPClient: client,
	}
}

/*GetHintsInProgressParams contains all the parameters to send to the API endpoint
for the get hints in progress operation typically these are written to a http.Request
*/
type GetHintsInProgressParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get hints in progress params
func (o *GetHintsInProgressParams) WithTimeout(timeout time.Duration) *GetHintsInProgressParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get hints in progress params
func (o *GetHintsInProgressParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get hints in progress params
func (o *GetHintsInProgressParams) WithContext(ctx context.Context) *GetHintsInProgressParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get hints in progress params
func (o *GetHintsInProgressParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get hints in progress params
func (o *GetHintsInProgressParams) WithHTTPClient(client *http.Client) *GetHintsInProgressParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get hints in progress params
func (o *GetHintsInProgressParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetHintsInProgressParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
