// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetCompactionThroughputMbPerSecReader is a Reader for the GetCompactionThroughputMbPerSec structure.
type GetCompactionThroughputMbPerSecReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCompactionThroughputMbPerSecReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetCompactionThroughputMbPerSecOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetCompactionThroughputMbPerSecOK creates a GetCompactionThroughputMbPerSecOK with default headers values
func NewGetCompactionThroughputMbPerSecOK() *GetCompactionThroughputMbPerSecOK {
	return &GetCompactionThroughputMbPerSecOK{}
}

/*GetCompactionThroughputMbPerSecOK handles this case with default header values.

GetCompactionThroughputMbPerSecOK get compaction throughput mb per sec o k
*/
type GetCompactionThroughputMbPerSecOK struct {
	Payload int32
}

func (o *GetCompactionThroughputMbPerSecOK) Error() string {
	return fmt.Sprintf("[GET /storage_service/compaction_throughput][%d] getCompactionThroughputMbPerSecOK  %+v", 200, o.Payload)
}

func (o *GetCompactionThroughputMbPerSecOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
