// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAllCfAllMemtablesOnHeapSizeParams creates a new GetAllCfAllMemtablesOnHeapSizeParams object
// with the default values initialized.
func NewGetAllCfAllMemtablesOnHeapSizeParams() *GetAllCfAllMemtablesOnHeapSizeParams {

	return &GetAllCfAllMemtablesOnHeapSizeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllCfAllMemtablesOnHeapSizeParamsWithTimeout creates a new GetAllCfAllMemtablesOnHeapSizeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAllCfAllMemtablesOnHeapSizeParamsWithTimeout(timeout time.Duration) *GetAllCfAllMemtablesOnHeapSizeParams {

	return &GetAllCfAllMemtablesOnHeapSizeParams{

		timeout: timeout,
	}
}

// NewGetAllCfAllMemtablesOnHeapSizeParamsWithContext creates a new GetAllCfAllMemtablesOnHeapSizeParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAllCfAllMemtablesOnHeapSizeParamsWithContext(ctx context.Context) *GetAllCfAllMemtablesOnHeapSizeParams {

	return &GetAllCfAllMemtablesOnHeapSizeParams{

		Context: ctx,
	}
}

// NewGetAllCfAllMemtablesOnHeapSizeParamsWithHTTPClient creates a new GetAllCfAllMemtablesOnHeapSizeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAllCfAllMemtablesOnHeapSizeParamsWithHTTPClient(client *http.Client) *GetAllCfAllMemtablesOnHeapSizeParams {

	return &GetAllCfAllMemtablesOnHeapSizeParams{
		HTTPClient: client,
	}
}

/*GetAllCfAllMemtablesOnHeapSizeParams contains all the parameters to send to the API endpoint
for the get all cf all memtables on heap size operation typically these are written to a http.Request
*/
type GetAllCfAllMemtablesOnHeapSizeParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get all cf all memtables on heap size params
func (o *GetAllCfAllMemtablesOnHeapSizeParams) WithTimeout(timeout time.Duration) *GetAllCfAllMemtablesOnHeapSizeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all cf all memtables on heap size params
func (o *GetAllCfAllMemtablesOnHeapSizeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all cf all memtables on heap size params
func (o *GetAllCfAllMemtablesOnHeapSizeParams) WithContext(ctx context.Context) *GetAllCfAllMemtablesOnHeapSizeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all cf all memtables on heap size params
func (o *GetAllCfAllMemtablesOnHeapSizeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get all cf all memtables on heap size params
func (o *GetAllCfAllMemtablesOnHeapSizeParams) WithHTTPClient(client *http.Client) *GetAllCfAllMemtablesOnHeapSizeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get all cf all memtables on heap size params
func (o *GetAllCfAllMemtablesOnHeapSizeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllCfAllMemtablesOnHeapSizeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
