// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetPendingMessagesParams creates a new GetPendingMessagesParams object
// with the default values initialized.
func NewGetPendingMessagesParams() *GetPendingMessagesParams {

	return &GetPendingMessagesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetPendingMessagesParamsWithTimeout creates a new GetPendingMessagesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetPendingMessagesParamsWithTimeout(timeout time.Duration) *GetPendingMessagesParams {

	return &GetPendingMessagesParams{

		timeout: timeout,
	}
}

// NewGetPendingMessagesParamsWithContext creates a new GetPendingMessagesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetPendingMessagesParamsWithContext(ctx context.Context) *GetPendingMessagesParams {

	return &GetPendingMessagesParams{

		Context: ctx,
	}
}

// NewGetPendingMessagesParamsWithHTTPClient creates a new GetPendingMessagesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetPendingMessagesParamsWithHTTPClient(client *http.Client) *GetPendingMessagesParams {

	return &GetPendingMessagesParams{
		HTTPClient: client,
	}
}

/*GetPendingMessagesParams contains all the parameters to send to the API endpoint
for the get pending messages operation typically these are written to a http.Request
*/
type GetPendingMessagesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get pending messages params
func (o *GetPendingMessagesParams) WithTimeout(timeout time.Duration) *GetPendingMessagesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get pending messages params
func (o *GetPendingMessagesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get pending messages params
func (o *GetPendingMessagesParams) WithContext(ctx context.Context) *GetPendingMessagesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get pending messages params
func (o *GetPendingMessagesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get pending messages params
func (o *GetPendingMessagesParams) WithHTTPClient(client *http.Client) *GetPendingMessagesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get pending messages params
func (o *GetPendingMessagesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetPendingMessagesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
