// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetAllCompressionRatioReader is a Reader for the GetAllCompressionRatio structure.
type GetAllCompressionRatioReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAllCompressionRatioReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAllCompressionRatioOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAllCompressionRatioOK creates a GetAllCompressionRatioOK with default headers values
func NewGetAllCompressionRatioOK() *GetAllCompressionRatioOK {
	return &GetAllCompressionRatioOK{}
}

/*GetAllCompressionRatioOK handles this case with default header values.

GetAllCompressionRatioOK get all compression ratio o k
*/
type GetAllCompressionRatioOK struct {
	Payload int32
}

func (o *GetAllCompressionRatioOK) Error() string {
	return fmt.Sprintf("[GET /column_family/metrics/compression_ratio][%d] getAllCompressionRatioOK  %+v", 200, o.Payload)
}

func (o *GetAllCompressionRatioOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
