// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/scylladb/mermaid/scylla/internal/models"
)

// GetCasProposeEstimatedRecentHistogramReader is a Reader for the GetCasProposeEstimatedRecentHistogram structure.
type GetCasProposeEstimatedRecentHistogramReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCasProposeEstimatedRecentHistogramReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetCasProposeEstimatedRecentHistogramOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetCasProposeEstimatedRecentHistogramOK creates a GetCasProposeEstimatedRecentHistogramOK with default headers values
func NewGetCasProposeEstimatedRecentHistogramOK() *GetCasProposeEstimatedRecentHistogramOK {
	return &GetCasProposeEstimatedRecentHistogramOK{}
}

/*GetCasProposeEstimatedRecentHistogramOK handles this case with default header values.

GetCasProposeEstimatedRecentHistogramOK get cas propose estimated recent histogram o k
*/
type GetCasProposeEstimatedRecentHistogramOK struct {
	Payload *models.EstimatedHistogram
}

func (o *GetCasProposeEstimatedRecentHistogramOK) Error() string {
	return fmt.Sprintf("[GET /column_family/metrics/cas_propose/estimated_recent_histogram/{name}][%d] getCasProposeEstimatedRecentHistogramOK  %+v", 200, o.Payload)
}

func (o *GetCasProposeEstimatedRecentHistogramOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EstimatedHistogram)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
