// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetKeyEntries1Reader is a Reader for the GetKeyEntries1 structure.
type GetKeyEntries1Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetKeyEntries1Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetKeyEntries1OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetKeyEntries1OK creates a GetKeyEntries1OK with default headers values
func NewGetKeyEntries1OK() *GetKeyEntries1OK {
	return &GetKeyEntries1OK{}
}

/*GetKeyEntries1OK handles this case with default header values.

GetKeyEntries1OK get key entries1 o k
*/
type GetKeyEntries1OK struct {
	Payload int32
}

func (o *GetKeyEntries1OK) Error() string {
	return fmt.Sprintf("[GET /cache_service/metrics/key/entries][%d] getKeyEntries1OK  %+v", 200, o.Payload)
}

func (o *GetKeyEntries1OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
