// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewIsStartingParams creates a new IsStartingParams object
// with the default values initialized.
func NewIsStartingParams() *IsStartingParams {

	return &IsStartingParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewIsStartingParamsWithTimeout creates a new IsStartingParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewIsStartingParamsWithTimeout(timeout time.Duration) *IsStartingParams {

	return &IsStartingParams{

		timeout: timeout,
	}
}

// NewIsStartingParamsWithContext creates a new IsStartingParams object
// with the default values initialized, and the ability to set a context for a request
func NewIsStartingParamsWithContext(ctx context.Context) *IsStartingParams {

	return &IsStartingParams{

		Context: ctx,
	}
}

// NewIsStartingParamsWithHTTPClient creates a new IsStartingParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewIsStartingParamsWithHTTPClient(client *http.Client) *IsStartingParams {

	return &IsStartingParams{
		HTTPClient: client,
	}
}

/*IsStartingParams contains all the parameters to send to the API endpoint
for the is starting operation typically these are written to a http.Request
*/
type IsStartingParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the is starting params
func (o *IsStartingParams) WithTimeout(timeout time.Duration) *IsStartingParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the is starting params
func (o *IsStartingParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the is starting params
func (o *IsStartingParams) WithContext(ctx context.Context) *IsStartingParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the is starting params
func (o *IsStartingParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the is starting params
func (o *IsStartingParams) WithHTTPClient(client *http.Client) *IsStartingParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the is starting params
func (o *IsStartingParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *IsStartingParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
