// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// ListEndpointsPendingHintsReader is a Reader for the ListEndpointsPendingHints structure.
type ListEndpointsPendingHintsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListEndpointsPendingHintsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewListEndpointsPendingHintsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListEndpointsPendingHintsOK creates a ListEndpointsPendingHintsOK with default headers values
func NewListEndpointsPendingHintsOK() *ListEndpointsPendingHintsOK {
	return &ListEndpointsPendingHintsOK{}
}

/*ListEndpointsPendingHintsOK handles this case with default header values.

ListEndpointsPendingHintsOK list endpoints pending hints o k
*/
type ListEndpointsPendingHintsOK struct {
	Payload []string
}

func (o *ListEndpointsPendingHintsOK) Error() string {
	return fmt.Sprintf("[GET /hinted_handoff/hints][%d] listEndpointsPendingHintsOK  %+v", 200, o.Payload)
}

func (o *ListEndpointsPendingHintsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
