// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewSetKeyCacheKeysToSave1Params creates a new SetKeyCacheKeysToSave1Params object
// with the default values initialized.
func NewSetKeyCacheKeysToSave1Params() *SetKeyCacheKeysToSave1Params {
	var ()
	return &SetKeyCacheKeysToSave1Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewSetKeyCacheKeysToSave1ParamsWithTimeout creates a new SetKeyCacheKeysToSave1Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewSetKeyCacheKeysToSave1ParamsWithTimeout(timeout time.Duration) *SetKeyCacheKeysToSave1Params {
	var ()
	return &SetKeyCacheKeysToSave1Params{

		timeout: timeout,
	}
}

// NewSetKeyCacheKeysToSave1ParamsWithContext creates a new SetKeyCacheKeysToSave1Params object
// with the default values initialized, and the ability to set a context for a request
func NewSetKeyCacheKeysToSave1ParamsWithContext(ctx context.Context) *SetKeyCacheKeysToSave1Params {
	var ()
	return &SetKeyCacheKeysToSave1Params{

		Context: ctx,
	}
}

// NewSetKeyCacheKeysToSave1ParamsWithHTTPClient creates a new SetKeyCacheKeysToSave1Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSetKeyCacheKeysToSave1ParamsWithHTTPClient(client *http.Client) *SetKeyCacheKeysToSave1Params {
	var ()
	return &SetKeyCacheKeysToSave1Params{
		HTTPClient: client,
	}
}

/*SetKeyCacheKeysToSave1Params contains all the parameters to send to the API endpoint
for the set key cache keys to save1 operation typically these are written to a http.Request
*/
type SetKeyCacheKeysToSave1Params struct {

	/*Kckts
	  key cache keys to save

	*/
	Kckts int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the set key cache keys to save1 params
func (o *SetKeyCacheKeysToSave1Params) WithTimeout(timeout time.Duration) *SetKeyCacheKeysToSave1Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the set key cache keys to save1 params
func (o *SetKeyCacheKeysToSave1Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the set key cache keys to save1 params
func (o *SetKeyCacheKeysToSave1Params) WithContext(ctx context.Context) *SetKeyCacheKeysToSave1Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the set key cache keys to save1 params
func (o *SetKeyCacheKeysToSave1Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the set key cache keys to save1 params
func (o *SetKeyCacheKeysToSave1Params) WithHTTPClient(client *http.Client) *SetKeyCacheKeysToSave1Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the set key cache keys to save1 params
func (o *SetKeyCacheKeysToSave1Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithKckts adds the kckts to the set key cache keys to save1 params
func (o *SetKeyCacheKeysToSave1Params) WithKckts(kckts int32) *SetKeyCacheKeysToSave1Params {
	o.SetKckts(kckts)
	return o
}

// SetKckts adds the kckts to the set key cache keys to save1 params
func (o *SetKeyCacheKeysToSave1Params) SetKckts(kckts int32) {
	o.Kckts = kckts
}

// WriteToRequest writes these params to a swagger request
func (o *SetKeyCacheKeysToSave1Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param kckts
	qrKckts := o.Kckts
	qKckts := swag.FormatInt32(qrKckts)
	if qKckts != "" {
		if err := r.SetQueryParam("kckts", qKckts); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
