// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// SetMaxHintWindowReader is a Reader for the SetMaxHintWindow structure.
type SetMaxHintWindowReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SetMaxHintWindowReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewSetMaxHintWindowOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSetMaxHintWindowOK creates a SetMaxHintWindowOK with default headers values
func NewSetMaxHintWindowOK() *SetMaxHintWindowOK {
	return &SetMaxHintWindowOK{}
}

/*SetMaxHintWindowOK handles this case with default header values.

SetMaxHintWindowOK set max hint window o k
*/
type SetMaxHintWindowOK struct {
}

func (o *SetMaxHintWindowOK) Error() string {
	return fmt.Sprintf("[POST /storage_proxy/max_hint_window][%d] setMaxHintWindowOK ", 200)
}

func (o *SetMaxHintWindowOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
