// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewSetTombstoneWarnThresholdParams creates a new SetTombstoneWarnThresholdParams object
// with the default values initialized.
func NewSetTombstoneWarnThresholdParams() *SetTombstoneWarnThresholdParams {
	var ()
	return &SetTombstoneWarnThresholdParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSetTombstoneWarnThresholdParamsWithTimeout creates a new SetTombstoneWarnThresholdParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSetTombstoneWarnThresholdParamsWithTimeout(timeout time.Duration) *SetTombstoneWarnThresholdParams {
	var ()
	return &SetTombstoneWarnThresholdParams{

		timeout: timeout,
	}
}

// NewSetTombstoneWarnThresholdParamsWithContext creates a new SetTombstoneWarnThresholdParams object
// with the default values initialized, and the ability to set a context for a request
func NewSetTombstoneWarnThresholdParamsWithContext(ctx context.Context) *SetTombstoneWarnThresholdParams {
	var ()
	return &SetTombstoneWarnThresholdParams{

		Context: ctx,
	}
}

// NewSetTombstoneWarnThresholdParamsWithHTTPClient creates a new SetTombstoneWarnThresholdParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSetTombstoneWarnThresholdParamsWithHTTPClient(client *http.Client) *SetTombstoneWarnThresholdParams {
	var ()
	return &SetTombstoneWarnThresholdParams{
		HTTPClient: client,
	}
}

/*SetTombstoneWarnThresholdParams contains all the parameters to send to the API endpoint
for the set tombstone warn threshold operation typically these are written to a http.Request
*/
type SetTombstoneWarnThresholdParams struct {

	/*DebugThreshold
	  tombstone debug threshold

	*/
	DebugThreshold int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the set tombstone warn threshold params
func (o *SetTombstoneWarnThresholdParams) WithTimeout(timeout time.Duration) *SetTombstoneWarnThresholdParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the set tombstone warn threshold params
func (o *SetTombstoneWarnThresholdParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the set tombstone warn threshold params
func (o *SetTombstoneWarnThresholdParams) WithContext(ctx context.Context) *SetTombstoneWarnThresholdParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the set tombstone warn threshold params
func (o *SetTombstoneWarnThresholdParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the set tombstone warn threshold params
func (o *SetTombstoneWarnThresholdParams) WithHTTPClient(client *http.Client) *SetTombstoneWarnThresholdParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the set tombstone warn threshold params
func (o *SetTombstoneWarnThresholdParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDebugThreshold adds the debugThreshold to the set tombstone warn threshold params
func (o *SetTombstoneWarnThresholdParams) WithDebugThreshold(debugThreshold int32) *SetTombstoneWarnThresholdParams {
	o.SetDebugThreshold(debugThreshold)
	return o
}

// SetDebugThreshold adds the debugThreshold to the set tombstone warn threshold params
func (o *SetTombstoneWarnThresholdParams) SetDebugThreshold(debugThreshold int32) {
	o.DebugThreshold = debugThreshold
}

// WriteToRequest writes these params to a swagger request
func (o *SetTombstoneWarnThresholdParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param debug_threshold
	qrDebugThreshold := o.DebugThreshold
	qDebugThreshold := swag.FormatInt32(qrDebugThreshold)
	if qDebugThreshold != "" {
		if err := r.SetQueryParam("debug_threshold", qDebugThreshold); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
