// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewStopNativeTransportParams creates a new StopNativeTransportParams object
// with the default values initialized.
func NewStopNativeTransportParams() *StopNativeTransportParams {

	return &StopNativeTransportParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewStopNativeTransportParamsWithTimeout creates a new StopNativeTransportParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewStopNativeTransportParamsWithTimeout(timeout time.Duration) *StopNativeTransportParams {

	return &StopNativeTransportParams{

		timeout: timeout,
	}
}

// NewStopNativeTransportParamsWithContext creates a new StopNativeTransportParams object
// with the default values initialized, and the ability to set a context for a request
func NewStopNativeTransportParamsWithContext(ctx context.Context) *StopNativeTransportParams {

	return &StopNativeTransportParams{

		Context: ctx,
	}
}

// NewStopNativeTransportParamsWithHTTPClient creates a new StopNativeTransportParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewStopNativeTransportParamsWithHTTPClient(client *http.Client) *StopNativeTransportParams {

	return &StopNativeTransportParams{
		HTTPClient: client,
	}
}

/*StopNativeTransportParams contains all the parameters to send to the API endpoint
for the stop native transport operation typically these are written to a http.Request
*/
type StopNativeTransportParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the stop native transport params
func (o *StopNativeTransportParams) WithTimeout(timeout time.Duration) *StopNativeTransportParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the stop native transport params
func (o *StopNativeTransportParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the stop native transport params
func (o *StopNativeTransportParams) WithContext(ctx context.Context) *StopNativeTransportParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the stop native transport params
func (o *StopNativeTransportParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the stop native transport params
func (o *StopNativeTransportParams) WithHTTPClient(client *http.Client) *StopNativeTransportParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the stop native transport params
func (o *StopNativeTransportParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *StopNativeTransportParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
