// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// UpdateSnitchReader is a Reader for the UpdateSnitch structure.
type UpdateSnitchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateSnitchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUpdateSnitchOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateSnitchOK creates a UpdateSnitchOK with default headers values
func NewUpdateSnitchOK() *UpdateSnitchOK {
	return &UpdateSnitchOK{}
}

/*UpdateSnitchOK handles this case with default header values.

UpdateSnitchOK update snitch o k
*/
type UpdateSnitchOK struct {
}

func (o *UpdateSnitchOK) Error() string {
	return fmt.Sprintf("[POST /storage_service/update_snitch][%d] updateSnitchOK ", 200)
}

func (o *UpdateSnitchOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
