// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewEnableAutoCompactionParams creates a new EnableAutoCompactionParams object
// with the default values initialized.
func NewEnableAutoCompactionParams() *EnableAutoCompactionParams {
	var ()
	return &EnableAutoCompactionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewEnableAutoCompactionParamsWithTimeout creates a new EnableAutoCompactionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewEnableAutoCompactionParamsWithTimeout(timeout time.Duration) *EnableAutoCompactionParams {
	var ()
	return &EnableAutoCompactionParams{

		timeout: timeout,
	}
}

// NewEnableAutoCompactionParamsWithContext creates a new EnableAutoCompactionParams object
// with the default values initialized, and the ability to set a context for a request
func NewEnableAutoCompactionParamsWithContext(ctx context.Context) *EnableAutoCompactionParams {
	var ()
	return &EnableAutoCompactionParams{

		Context: ctx,
	}
}

// NewEnableAutoCompactionParamsWithHTTPClient creates a new EnableAutoCompactionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewEnableAutoCompactionParamsWithHTTPClient(client *http.Client) *EnableAutoCompactionParams {
	var ()
	return &EnableAutoCompactionParams{
		HTTPClient: client,
	}
}

/*EnableAutoCompactionParams contains all the parameters to send to the API endpoint
for the enable auto compaction operation typically these are written to a http.Request
*/
type EnableAutoCompactionParams struct {

	/*Cf
	  Comma seperated column family names

	*/
	Cf *string
	/*Keyspace
	  The keyspace

	*/
	Keyspace string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the enable auto compaction params
func (o *EnableAutoCompactionParams) WithTimeout(timeout time.Duration) *EnableAutoCompactionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the enable auto compaction params
func (o *EnableAutoCompactionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the enable auto compaction params
func (o *EnableAutoCompactionParams) WithContext(ctx context.Context) *EnableAutoCompactionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the enable auto compaction params
func (o *EnableAutoCompactionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the enable auto compaction params
func (o *EnableAutoCompactionParams) WithHTTPClient(client *http.Client) *EnableAutoCompactionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the enable auto compaction params
func (o *EnableAutoCompactionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCf adds the cf to the enable auto compaction params
func (o *EnableAutoCompactionParams) WithCf(cf *string) *EnableAutoCompactionParams {
	o.SetCf(cf)
	return o
}

// SetCf adds the cf to the enable auto compaction params
func (o *EnableAutoCompactionParams) SetCf(cf *string) {
	o.Cf = cf
}

// WithKeyspace adds the keyspace to the enable auto compaction params
func (o *EnableAutoCompactionParams) WithKeyspace(keyspace string) *EnableAutoCompactionParams {
	o.SetKeyspace(keyspace)
	return o
}

// SetKeyspace adds the keyspace to the enable auto compaction params
func (o *EnableAutoCompactionParams) SetKeyspace(keyspace string) {
	o.Keyspace = keyspace
}

// WriteToRequest writes these params to a swagger request
func (o *EnableAutoCompactionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Cf != nil {

		// query param cf
		var qrCf string
		if o.Cf != nil {
			qrCf = *o.Cf
		}
		qCf := qrCf
		if qCf != "" {
			if err := r.SetQueryParam("cf", qCf); err != nil {
				return err
			}
		}

	}

	// path param keyspace
	if err := r.SetPathParam("keyspace", o.Keyspace); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
