// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// ForceUserDefinedCompactionReader is a Reader for the ForceUserDefinedCompaction structure.
type ForceUserDefinedCompactionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ForceUserDefinedCompactionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewForceUserDefinedCompactionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewForceUserDefinedCompactionOK creates a ForceUserDefinedCompactionOK with default headers values
func NewForceUserDefinedCompactionOK() *ForceUserDefinedCompactionOK {
	return &ForceUserDefinedCompactionOK{}
}

/*ForceUserDefinedCompactionOK handles this case with default header values.

ForceUserDefinedCompactionOK force user defined compaction o k
*/
type ForceUserDefinedCompactionOK struct {
}

func (o *ForceUserDefinedCompactionOK) Error() string {
	return fmt.Sprintf("[POST /compaction_manager/force_user_defined_compaction][%d] forceUserDefinedCompactionOK ", 200)
}

func (o *ForceUserDefinedCompactionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
