// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/scylladb/mermaid/dbapi/internal/models"
)

// GetRangeToEndpointMapReader is a Reader for the GetRangeToEndpointMap structure.
type GetRangeToEndpointMapReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRangeToEndpointMapReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetRangeToEndpointMapOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetRangeToEndpointMapOK creates a GetRangeToEndpointMapOK with default headers values
func NewGetRangeToEndpointMapOK() *GetRangeToEndpointMapOK {
	return &GetRangeToEndpointMapOK{}
}

/*GetRangeToEndpointMapOK handles this case with default header values.

GetRangeToEndpointMapOK get range to endpoint map o k
*/
type GetRangeToEndpointMapOK struct {
	Payload []*models.MaplistMapper
}

func (o *GetRangeToEndpointMapOK) Error() string {
	return fmt.Sprintf("[GET /storage_service/range_to_endpoint_map/{keyspace}][%d] getRangeToEndpointMapOK  %+v", 200, o.Payload)
}

func (o *GetRangeToEndpointMapOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
