// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetEndpointStateParams creates a new GetEndpointStateParams object
// with the default values initialized.
func NewGetEndpointStateParams() *GetEndpointStateParams {
	var ()
	return &GetEndpointStateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetEndpointStateParamsWithTimeout creates a new GetEndpointStateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetEndpointStateParamsWithTimeout(timeout time.Duration) *GetEndpointStateParams {
	var ()
	return &GetEndpointStateParams{

		timeout: timeout,
	}
}

// NewGetEndpointStateParamsWithContext creates a new GetEndpointStateParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetEndpointStateParamsWithContext(ctx context.Context) *GetEndpointStateParams {
	var ()
	return &GetEndpointStateParams{

		Context: ctx,
	}
}

// NewGetEndpointStateParamsWithHTTPClient creates a new GetEndpointStateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetEndpointStateParamsWithHTTPClient(client *http.Client) *GetEndpointStateParams {
	var ()
	return &GetEndpointStateParams{
		HTTPClient: client,
	}
}

/*GetEndpointStateParams contains all the parameters to send to the API endpoint
for the get endpoint state operation typically these are written to a http.Request
*/
type GetEndpointStateParams struct {

	/*Addr
	  The endpoint address

	*/
	Addr string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get endpoint state params
func (o *GetEndpointStateParams) WithTimeout(timeout time.Duration) *GetEndpointStateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get endpoint state params
func (o *GetEndpointStateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get endpoint state params
func (o *GetEndpointStateParams) WithContext(ctx context.Context) *GetEndpointStateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get endpoint state params
func (o *GetEndpointStateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get endpoint state params
func (o *GetEndpointStateParams) WithHTTPClient(client *http.Client) *GetEndpointStateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get endpoint state params
func (o *GetEndpointStateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAddr adds the addr to the get endpoint state params
func (o *GetEndpointStateParams) WithAddr(addr string) *GetEndpointStateParams {
	o.SetAddr(addr)
	return o
}

// SetAddr adds the addr to the get endpoint state params
func (o *GetEndpointStateParams) SetAddr(addr string) {
	o.Addr = addr
}

// WriteToRequest writes these params to a swagger request
func (o *GetEndpointStateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param addr
	if err := r.SetPathParam("addr", o.Addr); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
