// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetReadMetricsTimeoutsRatesParams creates a new GetReadMetricsTimeoutsRatesParams object
// with the default values initialized.
func NewGetReadMetricsTimeoutsRatesParams() *GetReadMetricsTimeoutsRatesParams {

	return &GetReadMetricsTimeoutsRatesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetReadMetricsTimeoutsRatesParamsWithTimeout creates a new GetReadMetricsTimeoutsRatesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetReadMetricsTimeoutsRatesParamsWithTimeout(timeout time.Duration) *GetReadMetricsTimeoutsRatesParams {

	return &GetReadMetricsTimeoutsRatesParams{

		timeout: timeout,
	}
}

// NewGetReadMetricsTimeoutsRatesParamsWithContext creates a new GetReadMetricsTimeoutsRatesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetReadMetricsTimeoutsRatesParamsWithContext(ctx context.Context) *GetReadMetricsTimeoutsRatesParams {

	return &GetReadMetricsTimeoutsRatesParams{

		Context: ctx,
	}
}

// NewGetReadMetricsTimeoutsRatesParamsWithHTTPClient creates a new GetReadMetricsTimeoutsRatesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetReadMetricsTimeoutsRatesParamsWithHTTPClient(client *http.Client) *GetReadMetricsTimeoutsRatesParams {

	return &GetReadMetricsTimeoutsRatesParams{
		HTTPClient: client,
	}
}

/*GetReadMetricsTimeoutsRatesParams contains all the parameters to send to the API endpoint
for the get read metrics timeouts rates operation typically these are written to a http.Request
*/
type GetReadMetricsTimeoutsRatesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get read metrics timeouts rates params
func (o *GetReadMetricsTimeoutsRatesParams) WithTimeout(timeout time.Duration) *GetReadMetricsTimeoutsRatesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get read metrics timeouts rates params
func (o *GetReadMetricsTimeoutsRatesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get read metrics timeouts rates params
func (o *GetReadMetricsTimeoutsRatesParams) WithContext(ctx context.Context) *GetReadMetricsTimeoutsRatesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get read metrics timeouts rates params
func (o *GetReadMetricsTimeoutsRatesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get read metrics timeouts rates params
func (o *GetReadMetricsTimeoutsRatesParams) WithHTTPClient(client *http.Client) *GetReadMetricsTimeoutsRatesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get read metrics timeouts rates params
func (o *GetReadMetricsTimeoutsRatesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetReadMetricsTimeoutsRatesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
