// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetLiveScannedHistogramParams creates a new GetLiveScannedHistogramParams object
// with the default values initialized.
func NewGetLiveScannedHistogramParams() *GetLiveScannedHistogramParams {
	var ()
	return &GetLiveScannedHistogramParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetLiveScannedHistogramParamsWithTimeout creates a new GetLiveScannedHistogramParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetLiveScannedHistogramParamsWithTimeout(timeout time.Duration) *GetLiveScannedHistogramParams {
	var ()
	return &GetLiveScannedHistogramParams{

		timeout: timeout,
	}
}

// NewGetLiveScannedHistogramParamsWithContext creates a new GetLiveScannedHistogramParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetLiveScannedHistogramParamsWithContext(ctx context.Context) *GetLiveScannedHistogramParams {
	var ()
	return &GetLiveScannedHistogramParams{

		Context: ctx,
	}
}

// NewGetLiveScannedHistogramParamsWithHTTPClient creates a new GetLiveScannedHistogramParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetLiveScannedHistogramParamsWithHTTPClient(client *http.Client) *GetLiveScannedHistogramParams {
	var ()
	return &GetLiveScannedHistogramParams{
		HTTPClient: client,
	}
}

/*GetLiveScannedHistogramParams contains all the parameters to send to the API endpoint
for the get live scanned histogram operation typically these are written to a http.Request
*/
type GetLiveScannedHistogramParams struct {

	/*Name
	  The column family name in keyspace:name format

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get live scanned histogram params
func (o *GetLiveScannedHistogramParams) WithTimeout(timeout time.Duration) *GetLiveScannedHistogramParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get live scanned histogram params
func (o *GetLiveScannedHistogramParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get live scanned histogram params
func (o *GetLiveScannedHistogramParams) WithContext(ctx context.Context) *GetLiveScannedHistogramParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get live scanned histogram params
func (o *GetLiveScannedHistogramParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get live scanned histogram params
func (o *GetLiveScannedHistogramParams) WithHTTPClient(client *http.Client) *GetLiveScannedHistogramParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get live scanned histogram params
func (o *GetLiveScannedHistogramParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get live scanned histogram params
func (o *GetLiveScannedHistogramParams) WithName(name string) *GetLiveScannedHistogramParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get live scanned histogram params
func (o *GetLiveScannedHistogramParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetLiveScannedHistogramParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
