// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetReleaseVersionParams creates a new GetReleaseVersionParams object
// with the default values initialized.
func NewGetReleaseVersionParams() *GetReleaseVersionParams {

	return &GetReleaseVersionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetReleaseVersionParamsWithTimeout creates a new GetReleaseVersionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetReleaseVersionParamsWithTimeout(timeout time.Duration) *GetReleaseVersionParams {

	return &GetReleaseVersionParams{

		timeout: timeout,
	}
}

// NewGetReleaseVersionParamsWithContext creates a new GetReleaseVersionParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetReleaseVersionParamsWithContext(ctx context.Context) *GetReleaseVersionParams {

	return &GetReleaseVersionParams{

		Context: ctx,
	}
}

// NewGetReleaseVersionParamsWithHTTPClient creates a new GetReleaseVersionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetReleaseVersionParamsWithHTTPClient(client *http.Client) *GetReleaseVersionParams {

	return &GetReleaseVersionParams{
		HTTPClient: client,
	}
}

/*GetReleaseVersionParams contains all the parameters to send to the API endpoint
for the get release version operation typically these are written to a http.Request
*/
type GetReleaseVersionParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get release version params
func (o *GetReleaseVersionParams) WithTimeout(timeout time.Duration) *GetReleaseVersionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get release version params
func (o *GetReleaseVersionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get release version params
func (o *GetReleaseVersionParams) WithContext(ctx context.Context) *GetReleaseVersionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get release version params
func (o *GetReleaseVersionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get release version params
func (o *GetReleaseVersionParams) WithHTTPClient(client *http.Client) *GetReleaseVersionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get release version params
func (o *GetReleaseVersionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetReleaseVersionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
