// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetBloomFilterOffHeapMemoryUsedParams creates a new GetBloomFilterOffHeapMemoryUsedParams object
// with the default values initialized.
func NewGetBloomFilterOffHeapMemoryUsedParams() *GetBloomFilterOffHeapMemoryUsedParams {
	var ()
	return &GetBloomFilterOffHeapMemoryUsedParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetBloomFilterOffHeapMemoryUsedParamsWithTimeout creates a new GetBloomFilterOffHeapMemoryUsedParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetBloomFilterOffHeapMemoryUsedParamsWithTimeout(timeout time.Duration) *GetBloomFilterOffHeapMemoryUsedParams {
	var ()
	return &GetBloomFilterOffHeapMemoryUsedParams{

		timeout: timeout,
	}
}

// NewGetBloomFilterOffHeapMemoryUsedParamsWithContext creates a new GetBloomFilterOffHeapMemoryUsedParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetBloomFilterOffHeapMemoryUsedParamsWithContext(ctx context.Context) *GetBloomFilterOffHeapMemoryUsedParams {
	var ()
	return &GetBloomFilterOffHeapMemoryUsedParams{

		Context: ctx,
	}
}

// NewGetBloomFilterOffHeapMemoryUsedParamsWithHTTPClient creates a new GetBloomFilterOffHeapMemoryUsedParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetBloomFilterOffHeapMemoryUsedParamsWithHTTPClient(client *http.Client) *GetBloomFilterOffHeapMemoryUsedParams {
	var ()
	return &GetBloomFilterOffHeapMemoryUsedParams{
		HTTPClient: client,
	}
}

/*GetBloomFilterOffHeapMemoryUsedParams contains all the parameters to send to the API endpoint
for the get bloom filter off heap memory used operation typically these are written to a http.Request
*/
type GetBloomFilterOffHeapMemoryUsedParams struct {

	/*Name
	  The column family name in keyspace:name format

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get bloom filter off heap memory used params
func (o *GetBloomFilterOffHeapMemoryUsedParams) WithTimeout(timeout time.Duration) *GetBloomFilterOffHeapMemoryUsedParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get bloom filter off heap memory used params
func (o *GetBloomFilterOffHeapMemoryUsedParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get bloom filter off heap memory used params
func (o *GetBloomFilterOffHeapMemoryUsedParams) WithContext(ctx context.Context) *GetBloomFilterOffHeapMemoryUsedParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get bloom filter off heap memory used params
func (o *GetBloomFilterOffHeapMemoryUsedParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get bloom filter off heap memory used params
func (o *GetBloomFilterOffHeapMemoryUsedParams) WithHTTPClient(client *http.Client) *GetBloomFilterOffHeapMemoryUsedParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get bloom filter off heap memory used params
func (o *GetBloomFilterOffHeapMemoryUsedParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get bloom filter off heap memory used params
func (o *GetBloomFilterOffHeapMemoryUsedParams) WithName(name string) *GetBloomFilterOffHeapMemoryUsedParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get bloom filter off heap memory used params
func (o *GetBloomFilterOffHeapMemoryUsedParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetBloomFilterOffHeapMemoryUsedParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
