// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetRowCacheHitParams creates a new GetRowCacheHitParams object
// with the default values initialized.
func NewGetRowCacheHitParams() *GetRowCacheHitParams {
	var ()
	return &GetRowCacheHitParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRowCacheHitParamsWithTimeout creates a new GetRowCacheHitParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRowCacheHitParamsWithTimeout(timeout time.Duration) *GetRowCacheHitParams {
	var ()
	return &GetRowCacheHitParams{

		timeout: timeout,
	}
}

// NewGetRowCacheHitParamsWithContext creates a new GetRowCacheHitParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRowCacheHitParamsWithContext(ctx context.Context) *GetRowCacheHitParams {
	var ()
	return &GetRowCacheHitParams{

		Context: ctx,
	}
}

// NewGetRowCacheHitParamsWithHTTPClient creates a new GetRowCacheHitParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRowCacheHitParamsWithHTTPClient(client *http.Client) *GetRowCacheHitParams {
	var ()
	return &GetRowCacheHitParams{
		HTTPClient: client,
	}
}

/*GetRowCacheHitParams contains all the parameters to send to the API endpoint
for the get row cache hit operation typically these are written to a http.Request
*/
type GetRowCacheHitParams struct {

	/*Name
	  The column family name in keyspace:name format

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get row cache hit params
func (o *GetRowCacheHitParams) WithTimeout(timeout time.Duration) *GetRowCacheHitParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get row cache hit params
func (o *GetRowCacheHitParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get row cache hit params
func (o *GetRowCacheHitParams) WithContext(ctx context.Context) *GetRowCacheHitParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get row cache hit params
func (o *GetRowCacheHitParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get row cache hit params
func (o *GetRowCacheHitParams) WithHTTPClient(client *http.Client) *GetRowCacheHitParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get row cache hit params
func (o *GetRowCacheHitParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get row cache hit params
func (o *GetRowCacheHitParams) WithName(name string) *GetRowCacheHitParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get row cache hit params
func (o *GetRowCacheHitParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetRowCacheHitParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
