// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetActiveSegmentNamesReader is a Reader for the GetActiveSegmentNames structure.
type GetActiveSegmentNamesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetActiveSegmentNamesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetActiveSegmentNamesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetActiveSegmentNamesOK creates a GetActiveSegmentNamesOK with default headers values
func NewGetActiveSegmentNamesOK() *GetActiveSegmentNamesOK {
	return &GetActiveSegmentNamesOK{}
}

/*GetActiveSegmentNamesOK handles this case with default header values.

GetActiveSegmentNamesOK get active segment names o k
*/
type GetActiveSegmentNamesOK struct {
	Payload []string
}

func (o *GetActiveSegmentNamesOK) Error() string {
	return fmt.Sprintf("[GET /commitlog/segments/active][%d] getActiveSegmentNamesOK  %+v", 200, o.Payload)
}

func (o *GetActiveSegmentNamesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
