// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCompressionParametersParams creates a new GetCompressionParametersParams object
// with the default values initialized.
func NewGetCompressionParametersParams() *GetCompressionParametersParams {
	var ()
	return &GetCompressionParametersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCompressionParametersParamsWithTimeout creates a new GetCompressionParametersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCompressionParametersParamsWithTimeout(timeout time.Duration) *GetCompressionParametersParams {
	var ()
	return &GetCompressionParametersParams{

		timeout: timeout,
	}
}

// NewGetCompressionParametersParamsWithContext creates a new GetCompressionParametersParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCompressionParametersParamsWithContext(ctx context.Context) *GetCompressionParametersParams {
	var ()
	return &GetCompressionParametersParams{

		Context: ctx,
	}
}

// NewGetCompressionParametersParamsWithHTTPClient creates a new GetCompressionParametersParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCompressionParametersParamsWithHTTPClient(client *http.Client) *GetCompressionParametersParams {
	var ()
	return &GetCompressionParametersParams{
		HTTPClient: client,
	}
}

/*GetCompressionParametersParams contains all the parameters to send to the API endpoint
for the get compression parameters operation typically these are written to a http.Request
*/
type GetCompressionParametersParams struct {

	/*Name
	  The column family name in keyspace:name format

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get compression parameters params
func (o *GetCompressionParametersParams) WithTimeout(timeout time.Duration) *GetCompressionParametersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get compression parameters params
func (o *GetCompressionParametersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get compression parameters params
func (o *GetCompressionParametersParams) WithContext(ctx context.Context) *GetCompressionParametersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get compression parameters params
func (o *GetCompressionParametersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get compression parameters params
func (o *GetCompressionParametersParams) WithHTTPClient(client *http.Client) *GetCompressionParametersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get compression parameters params
func (o *GetCompressionParametersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get compression parameters params
func (o *GetCompressionParametersParams) WithName(name string) *GetCompressionParametersParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get compression parameters params
func (o *GetCompressionParametersParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetCompressionParametersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
