// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAllLiveSsTableCountParams creates a new GetAllLiveSsTableCountParams object
// with the default values initialized.
func NewGetAllLiveSsTableCountParams() *GetAllLiveSsTableCountParams {

	return &GetAllLiveSsTableCountParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllLiveSsTableCountParamsWithTimeout creates a new GetAllLiveSsTableCountParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAllLiveSsTableCountParamsWithTimeout(timeout time.Duration) *GetAllLiveSsTableCountParams {

	return &GetAllLiveSsTableCountParams{

		timeout: timeout,
	}
}

// NewGetAllLiveSsTableCountParamsWithContext creates a new GetAllLiveSsTableCountParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAllLiveSsTableCountParamsWithContext(ctx context.Context) *GetAllLiveSsTableCountParams {

	return &GetAllLiveSsTableCountParams{

		Context: ctx,
	}
}

// NewGetAllLiveSsTableCountParamsWithHTTPClient creates a new GetAllLiveSsTableCountParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAllLiveSsTableCountParamsWithHTTPClient(client *http.Client) *GetAllLiveSsTableCountParams {

	return &GetAllLiveSsTableCountParams{
		HTTPClient: client,
	}
}

/*GetAllLiveSsTableCountParams contains all the parameters to send to the API endpoint
for the get all live ss table count operation typically these are written to a http.Request
*/
type GetAllLiveSsTableCountParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get all live ss table count params
func (o *GetAllLiveSsTableCountParams) WithTimeout(timeout time.Duration) *GetAllLiveSsTableCountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all live ss table count params
func (o *GetAllLiveSsTableCountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all live ss table count params
func (o *GetAllLiveSsTableCountParams) WithContext(ctx context.Context) *GetAllLiveSsTableCountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all live ss table count params
func (o *GetAllLiveSsTableCountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get all live ss table count params
func (o *GetAllLiveSsTableCountParams) WithHTTPClient(client *http.Client) *GetAllLiveSsTableCountParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get all live ss table count params
func (o *GetAllLiveSsTableCountParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllLiveSsTableCountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
