// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetTotalCompactionsCompletedParams creates a new GetTotalCompactionsCompletedParams object
// with the default values initialized.
func NewGetTotalCompactionsCompletedParams() *GetTotalCompactionsCompletedParams {

	return &GetTotalCompactionsCompletedParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetTotalCompactionsCompletedParamsWithTimeout creates a new GetTotalCompactionsCompletedParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetTotalCompactionsCompletedParamsWithTimeout(timeout time.Duration) *GetTotalCompactionsCompletedParams {

	return &GetTotalCompactionsCompletedParams{

		timeout: timeout,
	}
}

// NewGetTotalCompactionsCompletedParamsWithContext creates a new GetTotalCompactionsCompletedParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetTotalCompactionsCompletedParamsWithContext(ctx context.Context) *GetTotalCompactionsCompletedParams {

	return &GetTotalCompactionsCompletedParams{

		Context: ctx,
	}
}

// NewGetTotalCompactionsCompletedParamsWithHTTPClient creates a new GetTotalCompactionsCompletedParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetTotalCompactionsCompletedParamsWithHTTPClient(client *http.Client) *GetTotalCompactionsCompletedParams {

	return &GetTotalCompactionsCompletedParams{
		HTTPClient: client,
	}
}

/*GetTotalCompactionsCompletedParams contains all the parameters to send to the API endpoint
for the get total compactions completed operation typically these are written to a http.Request
*/
type GetTotalCompactionsCompletedParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get total compactions completed params
func (o *GetTotalCompactionsCompletedParams) WithTimeout(timeout time.Duration) *GetTotalCompactionsCompletedParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get total compactions completed params
func (o *GetTotalCompactionsCompletedParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get total compactions completed params
func (o *GetTotalCompactionsCompletedParams) WithContext(ctx context.Context) *GetTotalCompactionsCompletedParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get total compactions completed params
func (o *GetTotalCompactionsCompletedParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get total compactions completed params
func (o *GetTotalCompactionsCompletedParams) WithHTTPClient(client *http.Client) *GetTotalCompactionsCompletedParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get total compactions completed params
func (o *GetTotalCompactionsCompletedParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetTotalCompactionsCompletedParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
