// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetWriteRPCTimeoutReader is a Reader for the GetWriteRPCTimeout structure.
type GetWriteRPCTimeoutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetWriteRPCTimeoutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetWriteRPCTimeoutOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetWriteRPCTimeoutOK creates a GetWriteRPCTimeoutOK with default headers values
func NewGetWriteRPCTimeoutOK() *GetWriteRPCTimeoutOK {
	return &GetWriteRPCTimeoutOK{}
}

/*GetWriteRPCTimeoutOK handles this case with default header values.

GetWriteRPCTimeoutOK get write Rpc timeout o k
*/
type GetWriteRPCTimeoutOK struct {
	Payload int32
}

func (o *GetWriteRPCTimeoutOK) Error() string {
	return fmt.Sprintf("[GET /storage_proxy/write_rpc_timeout][%d] getWriteRpcTimeoutOK  %+v", 200, o.Payload)
}

func (o *GetWriteRPCTimeoutOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
