// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetArchivingSegmentNamesParams creates a new GetArchivingSegmentNamesParams object
// with the default values initialized.
func NewGetArchivingSegmentNamesParams() *GetArchivingSegmentNamesParams {

	return &GetArchivingSegmentNamesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetArchivingSegmentNamesParamsWithTimeout creates a new GetArchivingSegmentNamesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetArchivingSegmentNamesParamsWithTimeout(timeout time.Duration) *GetArchivingSegmentNamesParams {

	return &GetArchivingSegmentNamesParams{

		timeout: timeout,
	}
}

// NewGetArchivingSegmentNamesParamsWithContext creates a new GetArchivingSegmentNamesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetArchivingSegmentNamesParamsWithContext(ctx context.Context) *GetArchivingSegmentNamesParams {

	return &GetArchivingSegmentNamesParams{

		Context: ctx,
	}
}

// NewGetArchivingSegmentNamesParamsWithHTTPClient creates a new GetArchivingSegmentNamesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetArchivingSegmentNamesParamsWithHTTPClient(client *http.Client) *GetArchivingSegmentNamesParams {

	return &GetArchivingSegmentNamesParams{
		HTTPClient: client,
	}
}

/*GetArchivingSegmentNamesParams contains all the parameters to send to the API endpoint
for the get archiving segment names operation typically these are written to a http.Request
*/
type GetArchivingSegmentNamesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get archiving segment names params
func (o *GetArchivingSegmentNamesParams) WithTimeout(timeout time.Duration) *GetArchivingSegmentNamesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get archiving segment names params
func (o *GetArchivingSegmentNamesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get archiving segment names params
func (o *GetArchivingSegmentNamesParams) WithContext(ctx context.Context) *GetArchivingSegmentNamesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get archiving segment names params
func (o *GetArchivingSegmentNamesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get archiving segment names params
func (o *GetArchivingSegmentNamesParams) WithHTTPClient(client *http.Client) *GetArchivingSegmentNamesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get archiving segment names params
func (o *GetArchivingSegmentNamesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetArchivingSegmentNamesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
