// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSchemaVersionsParams creates a new GetSchemaVersionsParams object
// with the default values initialized.
func NewGetSchemaVersionsParams() *GetSchemaVersionsParams {

	return &GetSchemaVersionsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSchemaVersionsParamsWithTimeout creates a new GetSchemaVersionsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSchemaVersionsParamsWithTimeout(timeout time.Duration) *GetSchemaVersionsParams {

	return &GetSchemaVersionsParams{

		timeout: timeout,
	}
}

// NewGetSchemaVersionsParamsWithContext creates a new GetSchemaVersionsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSchemaVersionsParamsWithContext(ctx context.Context) *GetSchemaVersionsParams {

	return &GetSchemaVersionsParams{

		Context: ctx,
	}
}

// NewGetSchemaVersionsParamsWithHTTPClient creates a new GetSchemaVersionsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSchemaVersionsParamsWithHTTPClient(client *http.Client) *GetSchemaVersionsParams {

	return &GetSchemaVersionsParams{
		HTTPClient: client,
	}
}

/*GetSchemaVersionsParams contains all the parameters to send to the API endpoint
for the get schema versions operation typically these are written to a http.Request
*/
type GetSchemaVersionsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get schema versions params
func (o *GetSchemaVersionsParams) WithTimeout(timeout time.Duration) *GetSchemaVersionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get schema versions params
func (o *GetSchemaVersionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get schema versions params
func (o *GetSchemaVersionsParams) WithContext(ctx context.Context) *GetSchemaVersionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get schema versions params
func (o *GetSchemaVersionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get schema versions params
func (o *GetSchemaVersionsParams) WithHTTPClient(client *http.Client) *GetSchemaVersionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get schema versions params
func (o *GetSchemaVersionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetSchemaVersionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
