// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCasProposeParams creates a new GetCasProposeParams object
// with the default values initialized.
func NewGetCasProposeParams() *GetCasProposeParams {
	var ()
	return &GetCasProposeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCasProposeParamsWithTimeout creates a new GetCasProposeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCasProposeParamsWithTimeout(timeout time.Duration) *GetCasProposeParams {
	var ()
	return &GetCasProposeParams{

		timeout: timeout,
	}
}

// NewGetCasProposeParamsWithContext creates a new GetCasProposeParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCasProposeParamsWithContext(ctx context.Context) *GetCasProposeParams {
	var ()
	return &GetCasProposeParams{

		Context: ctx,
	}
}

// NewGetCasProposeParamsWithHTTPClient creates a new GetCasProposeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCasProposeParamsWithHTTPClient(client *http.Client) *GetCasProposeParams {
	var ()
	return &GetCasProposeParams{
		HTTPClient: client,
	}
}

/*GetCasProposeParams contains all the parameters to send to the API endpoint
for the get cas propose operation typically these are written to a http.Request
*/
type GetCasProposeParams struct {

	/*Name
	  The column family name in keyspace:name format

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get cas propose params
func (o *GetCasProposeParams) WithTimeout(timeout time.Duration) *GetCasProposeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get cas propose params
func (o *GetCasProposeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get cas propose params
func (o *GetCasProposeParams) WithContext(ctx context.Context) *GetCasProposeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get cas propose params
func (o *GetCasProposeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get cas propose params
func (o *GetCasProposeParams) WithHTTPClient(client *http.Client) *GetCasProposeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get cas propose params
func (o *GetCasProposeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get cas propose params
func (o *GetCasProposeParams) WithName(name string) *GetCasProposeParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get cas propose params
func (o *GetCasProposeParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetCasProposeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
