// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/scylladb/mermaid/dbapi/internal/models"
)

// GetCounterRequestsMovingAvrage1Reader is a Reader for the GetCounterRequestsMovingAvrage1 structure.
type GetCounterRequestsMovingAvrage1Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCounterRequestsMovingAvrage1Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetCounterRequestsMovingAvrage1OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetCounterRequestsMovingAvrage1OK creates a GetCounterRequestsMovingAvrage1OK with default headers values
func NewGetCounterRequestsMovingAvrage1OK() *GetCounterRequestsMovingAvrage1OK {
	return &GetCounterRequestsMovingAvrage1OK{}
}

/*GetCounterRequestsMovingAvrage1OK handles this case with default header values.

GetCounterRequestsMovingAvrage1OK get counter requests moving avrage1 o k
*/
type GetCounterRequestsMovingAvrage1OK struct {
	Payload *models.RateMovingAverage
}

func (o *GetCounterRequestsMovingAvrage1OK) Error() string {
	return fmt.Sprintf("[GET /cache_service/metrics/counter/requests_moving_avrage][%d] getCounterRequestsMovingAvrage1OK  %+v", 200, o.Payload)
}

func (o *GetCounterRequestsMovingAvrage1OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RateMovingAverage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
