// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAllLiveDiskSpaceUsedParams creates a new GetAllLiveDiskSpaceUsedParams object
// with the default values initialized.
func NewGetAllLiveDiskSpaceUsedParams() *GetAllLiveDiskSpaceUsedParams {

	return &GetAllLiveDiskSpaceUsedParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllLiveDiskSpaceUsedParamsWithTimeout creates a new GetAllLiveDiskSpaceUsedParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAllLiveDiskSpaceUsedParamsWithTimeout(timeout time.Duration) *GetAllLiveDiskSpaceUsedParams {

	return &GetAllLiveDiskSpaceUsedParams{

		timeout: timeout,
	}
}

// NewGetAllLiveDiskSpaceUsedParamsWithContext creates a new GetAllLiveDiskSpaceUsedParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAllLiveDiskSpaceUsedParamsWithContext(ctx context.Context) *GetAllLiveDiskSpaceUsedParams {

	return &GetAllLiveDiskSpaceUsedParams{

		Context: ctx,
	}
}

// NewGetAllLiveDiskSpaceUsedParamsWithHTTPClient creates a new GetAllLiveDiskSpaceUsedParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAllLiveDiskSpaceUsedParamsWithHTTPClient(client *http.Client) *GetAllLiveDiskSpaceUsedParams {

	return &GetAllLiveDiskSpaceUsedParams{
		HTTPClient: client,
	}
}

/*GetAllLiveDiskSpaceUsedParams contains all the parameters to send to the API endpoint
for the get all live disk space used operation typically these are written to a http.Request
*/
type GetAllLiveDiskSpaceUsedParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get all live disk space used params
func (o *GetAllLiveDiskSpaceUsedParams) WithTimeout(timeout time.Duration) *GetAllLiveDiskSpaceUsedParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all live disk space used params
func (o *GetAllLiveDiskSpaceUsedParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all live disk space used params
func (o *GetAllLiveDiskSpaceUsedParams) WithContext(ctx context.Context) *GetAllLiveDiskSpaceUsedParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all live disk space used params
func (o *GetAllLiveDiskSpaceUsedParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get all live disk space used params
func (o *GetAllLiveDiskSpaceUsedParams) WithHTTPClient(client *http.Client) *GetAllLiveDiskSpaceUsedParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get all live disk space used params
func (o *GetAllLiveDiskSpaceUsedParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllLiveDiskSpaceUsedParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
