// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAllIndexSummaryOffHeapMemoryUsedParams creates a new GetAllIndexSummaryOffHeapMemoryUsedParams object
// with the default values initialized.
func NewGetAllIndexSummaryOffHeapMemoryUsedParams() *GetAllIndexSummaryOffHeapMemoryUsedParams {

	return &GetAllIndexSummaryOffHeapMemoryUsedParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllIndexSummaryOffHeapMemoryUsedParamsWithTimeout creates a new GetAllIndexSummaryOffHeapMemoryUsedParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAllIndexSummaryOffHeapMemoryUsedParamsWithTimeout(timeout time.Duration) *GetAllIndexSummaryOffHeapMemoryUsedParams {

	return &GetAllIndexSummaryOffHeapMemoryUsedParams{

		timeout: timeout,
	}
}

// NewGetAllIndexSummaryOffHeapMemoryUsedParamsWithContext creates a new GetAllIndexSummaryOffHeapMemoryUsedParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAllIndexSummaryOffHeapMemoryUsedParamsWithContext(ctx context.Context) *GetAllIndexSummaryOffHeapMemoryUsedParams {

	return &GetAllIndexSummaryOffHeapMemoryUsedParams{

		Context: ctx,
	}
}

// NewGetAllIndexSummaryOffHeapMemoryUsedParamsWithHTTPClient creates a new GetAllIndexSummaryOffHeapMemoryUsedParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAllIndexSummaryOffHeapMemoryUsedParamsWithHTTPClient(client *http.Client) *GetAllIndexSummaryOffHeapMemoryUsedParams {

	return &GetAllIndexSummaryOffHeapMemoryUsedParams{
		HTTPClient: client,
	}
}

/*GetAllIndexSummaryOffHeapMemoryUsedParams contains all the parameters to send to the API endpoint
for the get all index summary off heap memory used operation typically these are written to a http.Request
*/
type GetAllIndexSummaryOffHeapMemoryUsedParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get all index summary off heap memory used params
func (o *GetAllIndexSummaryOffHeapMemoryUsedParams) WithTimeout(timeout time.Duration) *GetAllIndexSummaryOffHeapMemoryUsedParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all index summary off heap memory used params
func (o *GetAllIndexSummaryOffHeapMemoryUsedParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all index summary off heap memory used params
func (o *GetAllIndexSummaryOffHeapMemoryUsedParams) WithContext(ctx context.Context) *GetAllIndexSummaryOffHeapMemoryUsedParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all index summary off heap memory used params
func (o *GetAllIndexSummaryOffHeapMemoryUsedParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get all index summary off heap memory used params
func (o *GetAllIndexSummaryOffHeapMemoryUsedParams) WithHTTPClient(client *http.Client) *GetAllIndexSummaryOffHeapMemoryUsedParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get all index summary off heap memory used params
func (o *GetAllIndexSummaryOffHeapMemoryUsedParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllIndexSummaryOffHeapMemoryUsedParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
