// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetAllTotalDiskSpaceUsedReader is a Reader for the GetAllTotalDiskSpaceUsed structure.
type GetAllTotalDiskSpaceUsedReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAllTotalDiskSpaceUsedReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAllTotalDiskSpaceUsedOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAllTotalDiskSpaceUsedOK creates a GetAllTotalDiskSpaceUsedOK with default headers values
func NewGetAllTotalDiskSpaceUsedOK() *GetAllTotalDiskSpaceUsedOK {
	return &GetAllTotalDiskSpaceUsedOK{}
}

/*GetAllTotalDiskSpaceUsedOK handles this case with default header values.

GetAllTotalDiskSpaceUsedOK get all total disk space used o k
*/
type GetAllTotalDiskSpaceUsedOK struct {
	Payload int32
}

func (o *GetAllTotalDiskSpaceUsedOK) Error() string {
	return fmt.Sprintf("[GET /column_family/metrics/total_disk_space_used][%d] getAllTotalDiskSpaceUsedOK  %+v", 200, o.Payload)
}

func (o *GetAllTotalDiskSpaceUsedOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
