// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAllLoggerNamesParams creates a new GetAllLoggerNamesParams object
// with the default values initialized.
func NewGetAllLoggerNamesParams() *GetAllLoggerNamesParams {

	return &GetAllLoggerNamesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllLoggerNamesParamsWithTimeout creates a new GetAllLoggerNamesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAllLoggerNamesParamsWithTimeout(timeout time.Duration) *GetAllLoggerNamesParams {

	return &GetAllLoggerNamesParams{

		timeout: timeout,
	}
}

// NewGetAllLoggerNamesParamsWithContext creates a new GetAllLoggerNamesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAllLoggerNamesParamsWithContext(ctx context.Context) *GetAllLoggerNamesParams {

	return &GetAllLoggerNamesParams{

		Context: ctx,
	}
}

// NewGetAllLoggerNamesParamsWithHTTPClient creates a new GetAllLoggerNamesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAllLoggerNamesParamsWithHTTPClient(client *http.Client) *GetAllLoggerNamesParams {

	return &GetAllLoggerNamesParams{
		HTTPClient: client,
	}
}

/*GetAllLoggerNamesParams contains all the parameters to send to the API endpoint
for the get all logger names operation typically these are written to a http.Request
*/
type GetAllLoggerNamesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get all logger names params
func (o *GetAllLoggerNamesParams) WithTimeout(timeout time.Duration) *GetAllLoggerNamesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all logger names params
func (o *GetAllLoggerNamesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all logger names params
func (o *GetAllLoggerNamesParams) WithContext(ctx context.Context) *GetAllLoggerNamesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all logger names params
func (o *GetAllLoggerNamesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get all logger names params
func (o *GetAllLoggerNamesParams) WithHTTPClient(client *http.Client) *GetAllLoggerNamesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get all logger names params
func (o *GetAllLoggerNamesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllLoggerNamesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
