// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSlowQueryInfoParams creates a new GetSlowQueryInfoParams object
// with the default values initialized.
func NewGetSlowQueryInfoParams() *GetSlowQueryInfoParams {

	return &GetSlowQueryInfoParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSlowQueryInfoParamsWithTimeout creates a new GetSlowQueryInfoParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSlowQueryInfoParamsWithTimeout(timeout time.Duration) *GetSlowQueryInfoParams {

	return &GetSlowQueryInfoParams{

		timeout: timeout,
	}
}

// NewGetSlowQueryInfoParamsWithContext creates a new GetSlowQueryInfoParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSlowQueryInfoParamsWithContext(ctx context.Context) *GetSlowQueryInfoParams {

	return &GetSlowQueryInfoParams{

		Context: ctx,
	}
}

// NewGetSlowQueryInfoParamsWithHTTPClient creates a new GetSlowQueryInfoParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSlowQueryInfoParamsWithHTTPClient(client *http.Client) *GetSlowQueryInfoParams {

	return &GetSlowQueryInfoParams{
		HTTPClient: client,
	}
}

/*GetSlowQueryInfoParams contains all the parameters to send to the API endpoint
for the get slow query info operation typically these are written to a http.Request
*/
type GetSlowQueryInfoParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get slow query info params
func (o *GetSlowQueryInfoParams) WithTimeout(timeout time.Duration) *GetSlowQueryInfoParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get slow query info params
func (o *GetSlowQueryInfoParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get slow query info params
func (o *GetSlowQueryInfoParams) WithContext(ctx context.Context) *GetSlowQueryInfoParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get slow query info params
func (o *GetSlowQueryInfoParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get slow query info params
func (o *GetSlowQueryInfoParams) WithHTTPClient(client *http.Client) *GetSlowQueryInfoParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get slow query info params
func (o *GetSlowQueryInfoParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetSlowQueryInfoParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
