// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetWriteLatencyHistogramDepricatedParams creates a new GetWriteLatencyHistogramDepricatedParams object
// with the default values initialized.
func NewGetWriteLatencyHistogramDepricatedParams() *GetWriteLatencyHistogramDepricatedParams {
	var ()
	return &GetWriteLatencyHistogramDepricatedParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetWriteLatencyHistogramDepricatedParamsWithTimeout creates a new GetWriteLatencyHistogramDepricatedParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetWriteLatencyHistogramDepricatedParamsWithTimeout(timeout time.Duration) *GetWriteLatencyHistogramDepricatedParams {
	var ()
	return &GetWriteLatencyHistogramDepricatedParams{

		timeout: timeout,
	}
}

// NewGetWriteLatencyHistogramDepricatedParamsWithContext creates a new GetWriteLatencyHistogramDepricatedParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetWriteLatencyHistogramDepricatedParamsWithContext(ctx context.Context) *GetWriteLatencyHistogramDepricatedParams {
	var ()
	return &GetWriteLatencyHistogramDepricatedParams{

		Context: ctx,
	}
}

// NewGetWriteLatencyHistogramDepricatedParamsWithHTTPClient creates a new GetWriteLatencyHistogramDepricatedParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetWriteLatencyHistogramDepricatedParamsWithHTTPClient(client *http.Client) *GetWriteLatencyHistogramDepricatedParams {
	var ()
	return &GetWriteLatencyHistogramDepricatedParams{
		HTTPClient: client,
	}
}

/*GetWriteLatencyHistogramDepricatedParams contains all the parameters to send to the API endpoint
for the get write latency histogram depricated operation typically these are written to a http.Request
*/
type GetWriteLatencyHistogramDepricatedParams struct {

	/*Name
	  The column family name in keyspace:name format

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get write latency histogram depricated params
func (o *GetWriteLatencyHistogramDepricatedParams) WithTimeout(timeout time.Duration) *GetWriteLatencyHistogramDepricatedParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get write latency histogram depricated params
func (o *GetWriteLatencyHistogramDepricatedParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get write latency histogram depricated params
func (o *GetWriteLatencyHistogramDepricatedParams) WithContext(ctx context.Context) *GetWriteLatencyHistogramDepricatedParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get write latency histogram depricated params
func (o *GetWriteLatencyHistogramDepricatedParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get write latency histogram depricated params
func (o *GetWriteLatencyHistogramDepricatedParams) WithHTTPClient(client *http.Client) *GetWriteLatencyHistogramDepricatedParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get write latency histogram depricated params
func (o *GetWriteLatencyHistogramDepricatedParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get write latency histogram depricated params
func (o *GetWriteLatencyHistogramDepricatedParams) WithName(name string) *GetWriteLatencyHistogramDepricatedParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get write latency histogram depricated params
func (o *GetWriteLatencyHistogramDepricatedParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetWriteLatencyHistogramDepricatedParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
