// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetUnleveledSstablesParams creates a new GetUnleveledSstablesParams object
// with the default values initialized.
func NewGetUnleveledSstablesParams() *GetUnleveledSstablesParams {
	var ()
	return &GetUnleveledSstablesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetUnleveledSstablesParamsWithTimeout creates a new GetUnleveledSstablesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetUnleveledSstablesParamsWithTimeout(timeout time.Duration) *GetUnleveledSstablesParams {
	var ()
	return &GetUnleveledSstablesParams{

		timeout: timeout,
	}
}

// NewGetUnleveledSstablesParamsWithContext creates a new GetUnleveledSstablesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetUnleveledSstablesParamsWithContext(ctx context.Context) *GetUnleveledSstablesParams {
	var ()
	return &GetUnleveledSstablesParams{

		Context: ctx,
	}
}

// NewGetUnleveledSstablesParamsWithHTTPClient creates a new GetUnleveledSstablesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetUnleveledSstablesParamsWithHTTPClient(client *http.Client) *GetUnleveledSstablesParams {
	var ()
	return &GetUnleveledSstablesParams{
		HTTPClient: client,
	}
}

/*GetUnleveledSstablesParams contains all the parameters to send to the API endpoint
for the get unleveled sstables operation typically these are written to a http.Request
*/
type GetUnleveledSstablesParams struct {

	/*Name
	  The column family name in keyspace:name format

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get unleveled sstables params
func (o *GetUnleveledSstablesParams) WithTimeout(timeout time.Duration) *GetUnleveledSstablesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get unleveled sstables params
func (o *GetUnleveledSstablesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get unleveled sstables params
func (o *GetUnleveledSstablesParams) WithContext(ctx context.Context) *GetUnleveledSstablesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get unleveled sstables params
func (o *GetUnleveledSstablesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get unleveled sstables params
func (o *GetUnleveledSstablesParams) WithHTTPClient(client *http.Client) *GetUnleveledSstablesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get unleveled sstables params
func (o *GetUnleveledSstablesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get unleveled sstables params
func (o *GetUnleveledSstablesParams) WithName(name string) *GetUnleveledSstablesParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get unleveled sstables params
func (o *GetUnleveledSstablesParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetUnleveledSstablesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
