// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetRespondCompletedMessagesParams creates a new GetRespondCompletedMessagesParams object
// with the default values initialized.
func NewGetRespondCompletedMessagesParams() *GetRespondCompletedMessagesParams {

	return &GetRespondCompletedMessagesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRespondCompletedMessagesParamsWithTimeout creates a new GetRespondCompletedMessagesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRespondCompletedMessagesParamsWithTimeout(timeout time.Duration) *GetRespondCompletedMessagesParams {

	return &GetRespondCompletedMessagesParams{

		timeout: timeout,
	}
}

// NewGetRespondCompletedMessagesParamsWithContext creates a new GetRespondCompletedMessagesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRespondCompletedMessagesParamsWithContext(ctx context.Context) *GetRespondCompletedMessagesParams {

	return &GetRespondCompletedMessagesParams{

		Context: ctx,
	}
}

// NewGetRespondCompletedMessagesParamsWithHTTPClient creates a new GetRespondCompletedMessagesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRespondCompletedMessagesParamsWithHTTPClient(client *http.Client) *GetRespondCompletedMessagesParams {

	return &GetRespondCompletedMessagesParams{
		HTTPClient: client,
	}
}

/*GetRespondCompletedMessagesParams contains all the parameters to send to the API endpoint
for the get respond completed messages operation typically these are written to a http.Request
*/
type GetRespondCompletedMessagesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get respond completed messages params
func (o *GetRespondCompletedMessagesParams) WithTimeout(timeout time.Duration) *GetRespondCompletedMessagesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get respond completed messages params
func (o *GetRespondCompletedMessagesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get respond completed messages params
func (o *GetRespondCompletedMessagesParams) WithContext(ctx context.Context) *GetRespondCompletedMessagesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get respond completed messages params
func (o *GetRespondCompletedMessagesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get respond completed messages params
func (o *GetRespondCompletedMessagesParams) WithHTTPClient(client *http.Client) *GetRespondCompletedMessagesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get respond completed messages params
func (o *GetRespondCompletedMessagesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetRespondCompletedMessagesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
