// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/scylladb/mermaid/dbapi/internal/models"
)

// GetReadLatencyHistogramReader is a Reader for the GetReadLatencyHistogram structure.
type GetReadLatencyHistogramReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetReadLatencyHistogramReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetReadLatencyHistogramOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetReadLatencyHistogramOK creates a GetReadLatencyHistogramOK with default headers values
func NewGetReadLatencyHistogramOK() *GetReadLatencyHistogramOK {
	return &GetReadLatencyHistogramOK{}
}

/*GetReadLatencyHistogramOK handles this case with default header values.

GetReadLatencyHistogramOK get read latency histogram o k
*/
type GetReadLatencyHistogramOK struct {
	Payload *models.RateMovingAverageAndHistogram
}

func (o *GetReadLatencyHistogramOK) Error() string {
	return fmt.Sprintf("[GET /column_family/metrics/read_latency/moving_average_histogram/{name}][%d] getReadLatencyHistogramOK  %+v", 200, o.Payload)
}

func (o *GetReadLatencyHistogramOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RateMovingAverageAndHistogram)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
