// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetKeyRequests1Params creates a new GetKeyRequests1Params object
// with the default values initialized.
func NewGetKeyRequests1Params() *GetKeyRequests1Params {

	return &GetKeyRequests1Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetKeyRequests1ParamsWithTimeout creates a new GetKeyRequests1Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetKeyRequests1ParamsWithTimeout(timeout time.Duration) *GetKeyRequests1Params {

	return &GetKeyRequests1Params{

		timeout: timeout,
	}
}

// NewGetKeyRequests1ParamsWithContext creates a new GetKeyRequests1Params object
// with the default values initialized, and the ability to set a context for a request
func NewGetKeyRequests1ParamsWithContext(ctx context.Context) *GetKeyRequests1Params {

	return &GetKeyRequests1Params{

		Context: ctx,
	}
}

// NewGetKeyRequests1ParamsWithHTTPClient creates a new GetKeyRequests1Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetKeyRequests1ParamsWithHTTPClient(client *http.Client) *GetKeyRequests1Params {

	return &GetKeyRequests1Params{
		HTTPClient: client,
	}
}

/*GetKeyRequests1Params contains all the parameters to send to the API endpoint
for the get key requests1 operation typically these are written to a http.Request
*/
type GetKeyRequests1Params struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get key requests1 params
func (o *GetKeyRequests1Params) WithTimeout(timeout time.Duration) *GetKeyRequests1Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get key requests1 params
func (o *GetKeyRequests1Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get key requests1 params
func (o *GetKeyRequests1Params) WithContext(ctx context.Context) *GetKeyRequests1Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get key requests1 params
func (o *GetKeyRequests1Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get key requests1 params
func (o *GetKeyRequests1Params) WithHTTPClient(client *http.Client) *GetKeyRequests1Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get key requests1 params
func (o *GetKeyRequests1Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetKeyRequests1Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
