// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetLiveDiskSpaceUsedParams creates a new GetLiveDiskSpaceUsedParams object
// with the default values initialized.
func NewGetLiveDiskSpaceUsedParams() *GetLiveDiskSpaceUsedParams {
	var ()
	return &GetLiveDiskSpaceUsedParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetLiveDiskSpaceUsedParamsWithTimeout creates a new GetLiveDiskSpaceUsedParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetLiveDiskSpaceUsedParamsWithTimeout(timeout time.Duration) *GetLiveDiskSpaceUsedParams {
	var ()
	return &GetLiveDiskSpaceUsedParams{

		timeout: timeout,
	}
}

// NewGetLiveDiskSpaceUsedParamsWithContext creates a new GetLiveDiskSpaceUsedParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetLiveDiskSpaceUsedParamsWithContext(ctx context.Context) *GetLiveDiskSpaceUsedParams {
	var ()
	return &GetLiveDiskSpaceUsedParams{

		Context: ctx,
	}
}

// NewGetLiveDiskSpaceUsedParamsWithHTTPClient creates a new GetLiveDiskSpaceUsedParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetLiveDiskSpaceUsedParamsWithHTTPClient(client *http.Client) *GetLiveDiskSpaceUsedParams {
	var ()
	return &GetLiveDiskSpaceUsedParams{
		HTTPClient: client,
	}
}

/*GetLiveDiskSpaceUsedParams contains all the parameters to send to the API endpoint
for the get live disk space used operation typically these are written to a http.Request
*/
type GetLiveDiskSpaceUsedParams struct {

	/*Name
	  The column family name in keyspace:name format

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get live disk space used params
func (o *GetLiveDiskSpaceUsedParams) WithTimeout(timeout time.Duration) *GetLiveDiskSpaceUsedParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get live disk space used params
func (o *GetLiveDiskSpaceUsedParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get live disk space used params
func (o *GetLiveDiskSpaceUsedParams) WithContext(ctx context.Context) *GetLiveDiskSpaceUsedParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get live disk space used params
func (o *GetLiveDiskSpaceUsedParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get live disk space used params
func (o *GetLiveDiskSpaceUsedParams) WithHTTPClient(client *http.Client) *GetLiveDiskSpaceUsedParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get live disk space used params
func (o *GetLiveDiskSpaceUsedParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get live disk space used params
func (o *GetLiveDiskSpaceUsedParams) WithName(name string) *GetLiveDiskSpaceUsedParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get live disk space used params
func (o *GetLiveDiskSpaceUsedParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetLiveDiskSpaceUsedParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
