// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetCounterEntries1Reader is a Reader for the GetCounterEntries1 structure.
type GetCounterEntries1Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCounterEntries1Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetCounterEntries1OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetCounterEntries1OK creates a GetCounterEntries1OK with default headers values
func NewGetCounterEntries1OK() *GetCounterEntries1OK {
	return &GetCounterEntries1OK{}
}

/*GetCounterEntries1OK handles this case with default header values.

GetCounterEntries1OK get counter entries1 o k
*/
type GetCounterEntries1OK struct {
	Payload int32
}

func (o *GetCounterEntries1OK) Error() string {
	return fmt.Sprintf("[GET /cache_service/metrics/counter/entries][%d] getCounterEntries1OK  %+v", 200, o.Payload)
}

func (o *GetCounterEntries1OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
