// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetActiveSegmentNamesParams creates a new GetActiveSegmentNamesParams object
// with the default values initialized.
func NewGetActiveSegmentNamesParams() *GetActiveSegmentNamesParams {

	return &GetActiveSegmentNamesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetActiveSegmentNamesParamsWithTimeout creates a new GetActiveSegmentNamesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetActiveSegmentNamesParamsWithTimeout(timeout time.Duration) *GetActiveSegmentNamesParams {

	return &GetActiveSegmentNamesParams{

		timeout: timeout,
	}
}

// NewGetActiveSegmentNamesParamsWithContext creates a new GetActiveSegmentNamesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetActiveSegmentNamesParamsWithContext(ctx context.Context) *GetActiveSegmentNamesParams {

	return &GetActiveSegmentNamesParams{

		Context: ctx,
	}
}

// NewGetActiveSegmentNamesParamsWithHTTPClient creates a new GetActiveSegmentNamesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetActiveSegmentNamesParamsWithHTTPClient(client *http.Client) *GetActiveSegmentNamesParams {

	return &GetActiveSegmentNamesParams{
		HTTPClient: client,
	}
}

/*GetActiveSegmentNamesParams contains all the parameters to send to the API endpoint
for the get active segment names operation typically these are written to a http.Request
*/
type GetActiveSegmentNamesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get active segment names params
func (o *GetActiveSegmentNamesParams) WithTimeout(timeout time.Duration) *GetActiveSegmentNamesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get active segment names params
func (o *GetActiveSegmentNamesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get active segment names params
func (o *GetActiveSegmentNamesParams) WithContext(ctx context.Context) *GetActiveSegmentNamesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get active segment names params
func (o *GetActiveSegmentNamesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get active segment names params
func (o *GetActiveSegmentNamesParams) WithHTTPClient(client *http.Client) *GetActiveSegmentNamesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get active segment names params
func (o *GetActiveSegmentNamesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetActiveSegmentNamesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
