// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewIsJoinedParams creates a new IsJoinedParams object
// with the default values initialized.
func NewIsJoinedParams() *IsJoinedParams {

	return &IsJoinedParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewIsJoinedParamsWithTimeout creates a new IsJoinedParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewIsJoinedParamsWithTimeout(timeout time.Duration) *IsJoinedParams {

	return &IsJoinedParams{

		timeout: timeout,
	}
}

// NewIsJoinedParamsWithContext creates a new IsJoinedParams object
// with the default values initialized, and the ability to set a context for a request
func NewIsJoinedParamsWithContext(ctx context.Context) *IsJoinedParams {

	return &IsJoinedParams{

		Context: ctx,
	}
}

// NewIsJoinedParamsWithHTTPClient creates a new IsJoinedParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewIsJoinedParamsWithHTTPClient(client *http.Client) *IsJoinedParams {

	return &IsJoinedParams{
		HTTPClient: client,
	}
}

/*IsJoinedParams contains all the parameters to send to the API endpoint
for the is joined operation typically these are written to a http.Request
*/
type IsJoinedParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the is joined params
func (o *IsJoinedParams) WithTimeout(timeout time.Duration) *IsJoinedParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the is joined params
func (o *IsJoinedParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the is joined params
func (o *IsJoinedParams) WithContext(ctx context.Context) *IsJoinedParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the is joined params
func (o *IsJoinedParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the is joined params
func (o *IsJoinedParams) WithHTTPClient(client *http.Client) *IsJoinedParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the is joined params
func (o *IsJoinedParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *IsJoinedParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
