// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewIsNativeTransportRunningParams creates a new IsNativeTransportRunningParams object
// with the default values initialized.
func NewIsNativeTransportRunningParams() *IsNativeTransportRunningParams {

	return &IsNativeTransportRunningParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewIsNativeTransportRunningParamsWithTimeout creates a new IsNativeTransportRunningParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewIsNativeTransportRunningParamsWithTimeout(timeout time.Duration) *IsNativeTransportRunningParams {

	return &IsNativeTransportRunningParams{

		timeout: timeout,
	}
}

// NewIsNativeTransportRunningParamsWithContext creates a new IsNativeTransportRunningParams object
// with the default values initialized, and the ability to set a context for a request
func NewIsNativeTransportRunningParamsWithContext(ctx context.Context) *IsNativeTransportRunningParams {

	return &IsNativeTransportRunningParams{

		Context: ctx,
	}
}

// NewIsNativeTransportRunningParamsWithHTTPClient creates a new IsNativeTransportRunningParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewIsNativeTransportRunningParamsWithHTTPClient(client *http.Client) *IsNativeTransportRunningParams {

	return &IsNativeTransportRunningParams{
		HTTPClient: client,
	}
}

/*IsNativeTransportRunningParams contains all the parameters to send to the API endpoint
for the is native transport running operation typically these are written to a http.Request
*/
type IsNativeTransportRunningParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the is native transport running params
func (o *IsNativeTransportRunningParams) WithTimeout(timeout time.Duration) *IsNativeTransportRunningParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the is native transport running params
func (o *IsNativeTransportRunningParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the is native transport running params
func (o *IsNativeTransportRunningParams) WithContext(ctx context.Context) *IsNativeTransportRunningParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the is native transport running params
func (o *IsNativeTransportRunningParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the is native transport running params
func (o *IsNativeTransportRunningParams) WithHTTPClient(client *http.Client) *IsNativeTransportRunningParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the is native transport running params
func (o *IsNativeTransportRunningParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *IsNativeTransportRunningParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
