// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewSetCompressionParametersParams creates a new SetCompressionParametersParams object
// with the default values initialized.
func NewSetCompressionParametersParams() *SetCompressionParametersParams {
	var ()
	return &SetCompressionParametersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSetCompressionParametersParamsWithTimeout creates a new SetCompressionParametersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSetCompressionParametersParamsWithTimeout(timeout time.Duration) *SetCompressionParametersParams {
	var ()
	return &SetCompressionParametersParams{

		timeout: timeout,
	}
}

// NewSetCompressionParametersParamsWithContext creates a new SetCompressionParametersParams object
// with the default values initialized, and the ability to set a context for a request
func NewSetCompressionParametersParamsWithContext(ctx context.Context) *SetCompressionParametersParams {
	var ()
	return &SetCompressionParametersParams{

		Context: ctx,
	}
}

// NewSetCompressionParametersParamsWithHTTPClient creates a new SetCompressionParametersParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSetCompressionParametersParamsWithHTTPClient(client *http.Client) *SetCompressionParametersParams {
	var ()
	return &SetCompressionParametersParams{
		HTTPClient: client,
	}
}

/*SetCompressionParametersParams contains all the parameters to send to the API endpoint
for the set compression parameters operation typically these are written to a http.Request
*/
type SetCompressionParametersParams struct {

	/*Name
	  The column family name in keyspace:name format

	*/
	Name string
	/*Opts
	  The options to set

	*/
	Opts string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the set compression parameters params
func (o *SetCompressionParametersParams) WithTimeout(timeout time.Duration) *SetCompressionParametersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the set compression parameters params
func (o *SetCompressionParametersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the set compression parameters params
func (o *SetCompressionParametersParams) WithContext(ctx context.Context) *SetCompressionParametersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the set compression parameters params
func (o *SetCompressionParametersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the set compression parameters params
func (o *SetCompressionParametersParams) WithHTTPClient(client *http.Client) *SetCompressionParametersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the set compression parameters params
func (o *SetCompressionParametersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the set compression parameters params
func (o *SetCompressionParametersParams) WithName(name string) *SetCompressionParametersParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the set compression parameters params
func (o *SetCompressionParametersParams) SetName(name string) {
	o.Name = name
}

// WithOpts adds the opts to the set compression parameters params
func (o *SetCompressionParametersParams) WithOpts(opts string) *SetCompressionParametersParams {
	o.SetOpts(opts)
	return o
}

// SetOpts adds the opts to the set compression parameters params
func (o *SetCompressionParametersParams) SetOpts(opts string) {
	o.Opts = opts
}

// WriteToRequest writes these params to a swagger request
func (o *SetCompressionParametersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// query param opts
	qrOpts := o.Opts
	qOpts := qrOpts
	if qOpts != "" {
		if err := r.SetQueryParam("opts", qOpts); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
