// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewSetCompactionStrategyClassParams creates a new SetCompactionStrategyClassParams object
// with the default values initialized.
func NewSetCompactionStrategyClassParams() *SetCompactionStrategyClassParams {
	var ()
	return &SetCompactionStrategyClassParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSetCompactionStrategyClassParamsWithTimeout creates a new SetCompactionStrategyClassParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSetCompactionStrategyClassParamsWithTimeout(timeout time.Duration) *SetCompactionStrategyClassParams {
	var ()
	return &SetCompactionStrategyClassParams{

		timeout: timeout,
	}
}

// NewSetCompactionStrategyClassParamsWithContext creates a new SetCompactionStrategyClassParams object
// with the default values initialized, and the ability to set a context for a request
func NewSetCompactionStrategyClassParamsWithContext(ctx context.Context) *SetCompactionStrategyClassParams {
	var ()
	return &SetCompactionStrategyClassParams{

		Context: ctx,
	}
}

// NewSetCompactionStrategyClassParamsWithHTTPClient creates a new SetCompactionStrategyClassParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSetCompactionStrategyClassParamsWithHTTPClient(client *http.Client) *SetCompactionStrategyClassParams {
	var ()
	return &SetCompactionStrategyClassParams{
		HTTPClient: client,
	}
}

/*SetCompactionStrategyClassParams contains all the parameters to send to the API endpoint
for the set compaction strategy class operation typically these are written to a http.Request
*/
type SetCompactionStrategyClassParams struct {

	/*ClassName
	  The class name

	*/
	ClassName string
	/*Name
	  The column family name in keyspace:name format

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the set compaction strategy class params
func (o *SetCompactionStrategyClassParams) WithTimeout(timeout time.Duration) *SetCompactionStrategyClassParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the set compaction strategy class params
func (o *SetCompactionStrategyClassParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the set compaction strategy class params
func (o *SetCompactionStrategyClassParams) WithContext(ctx context.Context) *SetCompactionStrategyClassParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the set compaction strategy class params
func (o *SetCompactionStrategyClassParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the set compaction strategy class params
func (o *SetCompactionStrategyClassParams) WithHTTPClient(client *http.Client) *SetCompactionStrategyClassParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the set compaction strategy class params
func (o *SetCompactionStrategyClassParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithClassName adds the className to the set compaction strategy class params
func (o *SetCompactionStrategyClassParams) WithClassName(className string) *SetCompactionStrategyClassParams {
	o.SetClassName(className)
	return o
}

// SetClassName adds the className to the set compaction strategy class params
func (o *SetCompactionStrategyClassParams) SetClassName(className string) {
	o.ClassName = className
}

// WithName adds the name to the set compaction strategy class params
func (o *SetCompactionStrategyClassParams) WithName(name string) *SetCompactionStrategyClassParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the set compaction strategy class params
func (o *SetCompactionStrategyClassParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *SetCompactionStrategyClassParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param class_name
	qrClassName := o.ClassName
	qClassName := qrClassName
	if qClassName != "" {
		if err := r.SetQueryParam("class_name", qClassName); err != nil {
			return err
		}
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
