// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewSetLoggerLevelParams creates a new SetLoggerLevelParams object
// with the default values initialized.
func NewSetLoggerLevelParams() *SetLoggerLevelParams {
	var ()
	return &SetLoggerLevelParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSetLoggerLevelParamsWithTimeout creates a new SetLoggerLevelParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSetLoggerLevelParamsWithTimeout(timeout time.Duration) *SetLoggerLevelParams {
	var ()
	return &SetLoggerLevelParams{

		timeout: timeout,
	}
}

// NewSetLoggerLevelParamsWithContext creates a new SetLoggerLevelParams object
// with the default values initialized, and the ability to set a context for a request
func NewSetLoggerLevelParamsWithContext(ctx context.Context) *SetLoggerLevelParams {
	var ()
	return &SetLoggerLevelParams{

		Context: ctx,
	}
}

// NewSetLoggerLevelParamsWithHTTPClient creates a new SetLoggerLevelParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSetLoggerLevelParamsWithHTTPClient(client *http.Client) *SetLoggerLevelParams {
	var ()
	return &SetLoggerLevelParams{
		HTTPClient: client,
	}
}

/*SetLoggerLevelParams contains all the parameters to send to the API endpoint
for the set logger level operation typically these are written to a http.Request
*/
type SetLoggerLevelParams struct {

	/*Level
	  The new log level

	*/
	Level string
	/*Name
	  The logger to query about

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the set logger level params
func (o *SetLoggerLevelParams) WithTimeout(timeout time.Duration) *SetLoggerLevelParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the set logger level params
func (o *SetLoggerLevelParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the set logger level params
func (o *SetLoggerLevelParams) WithContext(ctx context.Context) *SetLoggerLevelParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the set logger level params
func (o *SetLoggerLevelParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the set logger level params
func (o *SetLoggerLevelParams) WithHTTPClient(client *http.Client) *SetLoggerLevelParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the set logger level params
func (o *SetLoggerLevelParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLevel adds the level to the set logger level params
func (o *SetLoggerLevelParams) WithLevel(level string) *SetLoggerLevelParams {
	o.SetLevel(level)
	return o
}

// SetLevel adds the level to the set logger level params
func (o *SetLoggerLevelParams) SetLevel(level string) {
	o.Level = level
}

// WithName adds the name to the set logger level params
func (o *SetLoggerLevelParams) WithName(name string) *SetLoggerLevelParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the set logger level params
func (o *SetLoggerLevelParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *SetLoggerLevelParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param level
	qrLevel := o.Level
	qLevel := qrLevel
	if qLevel != "" {
		if err := r.SetQueryParam("level", qLevel); err != nil {
			return err
		}
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
