// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// SetHintedHandoffEnabledByDcListReader is a Reader for the SetHintedHandoffEnabledByDcList structure.
type SetHintedHandoffEnabledByDcListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SetHintedHandoffEnabledByDcListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewSetHintedHandoffEnabledByDcListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSetHintedHandoffEnabledByDcListOK creates a SetHintedHandoffEnabledByDcListOK with default headers values
func NewSetHintedHandoffEnabledByDcListOK() *SetHintedHandoffEnabledByDcListOK {
	return &SetHintedHandoffEnabledByDcListOK{}
}

/*SetHintedHandoffEnabledByDcListOK handles this case with default header values.

SetHintedHandoffEnabledByDcListOK set hinted handoff enabled by dc list o k
*/
type SetHintedHandoffEnabledByDcListOK struct {
}

func (o *SetHintedHandoffEnabledByDcListOK) Error() string {
	return fmt.Sprintf("[POST /storage_proxy/hinted_handoff_enabled_by_dc][%d] setHintedHandoffEnabledByDcListOK ", 200)
}

func (o *SetHintedHandoffEnabledByDcListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
